bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "Successfully finish 6 magicians",
    "Hit all 6 cages in 3 different levels",
    "7 unique World map cage medallions",
    "Kill 7 unique Greenbois",
    "Reach 30 Lives",
    "Touch all 13 fairies in Band land",
    "Get 2 lives from 1 Magician",
    "Max% Pink Plant Woods",
    "Kill 6 unique tall living stones in PPW without using punch and without taking damage in between",
    "Beat the 2nd PPW Magician under 27 seconds on your first visit to the level",
    "Beat the PPW2 Magician under 8 seconds",
    "Get all cages in AL without leaving the level",
    "Enter AL for the first time with 13 lives and 5 cages",
    "Beat both Bzzit & Moskito without using Jump and without taking damage",
    "AL Screen 3 Max% and damageless (autoscroller)",
    "In Swamps screen 3, go from the bottom to top without taking damage and without using helicopter",
    "Clip 6 times in the Swamps screen 1",
    "Beat the Swamps Magician under 17 seconds without using helicopter and run",
    "Max% The Swamps of Forgetfulness",
    "Beat Moskito after beating Mr. Sax",
    "Get all 3 MN screen 1 cages without using speed storage",
    "Beat Moskito's Nest by only using 1 punch",
    "Kill all enemies in MN screen 1 without getting hit (kill all piranha's once)",
    "Beat the dark screen of bongo hills without collecting anything and without getting hit",
    "Beat the BH4 Magician under 23 seconds without using helicopter and run",
    "Get all 6 1ups in Bongo Hills",
    "Beat Bongo hills without dying and without taking damage while getting all cages",
    "Max% Allegro Presto",
    "Beat Allegro screen 1 while collecting 4 tings or less",
    "Do Allegro clip twice within 5 tries",
    "Beat Allegro Presto without having the ring grab powerup",
    "Collect 5 cages in TG without getting hit",
    "Get all cages in TG without using helicopter or superjumps",
    "Beat TG screen 2 without taking a hit",
    "Perform Double golem jump in TG",
    "Damageless Hard Rocks",
    "Touch all the endsigns of Hard Rocks and SMC",
    "Beat the final screen of Hard rocks while only allowed to touch 4 unique clouds",
    "Get all 7 1ups in Hard Rocks",
    "Collect all 51 tings in MSP1 and reach the endsign without taking a hit",
    "Hit Mr. Stone 6 times while having atleast 3 dogs alive all the time",
    "Punch Mr. Stone off the screen",
    "Beat Mr. Stone Peaks after getting 4 cages in Hard Rocks",
    "Beat Gong Heights screen 2 without letting go of right and without crawling",
    "Get all Gong Heights cages in reverse order",
    "Beat Gong Heights screen 1 while only touching one bongo",
    "Beat Gong Heights without using helicopter and run",
    "Enter Mr Sax fight (chase screen) while having exactly 69 tings",
    "Beat mr sax using only 12 punches and without getting hit",
    "Beat the first screen of Mr. Sax as small rayman",
    "Clip 5 times in Mr. Sax without pressing down",
    "Get all 7 1ups in EP",
    "Grab 2 lives as small rayman on EP2",
    "Beat the EP 3 Magician under 27 seconds",
    "Beat EP without using helicopter and run",
    "Beat the first screen of PP as small rayman",
    "Beat PP without using helicopter and run in screens 1 and 3",
    "in PP2, Collect all 60 tings & reach the endsign without taking a hit",
    "Beat the final screen of PP with the speedstorage strat on the sharpeners",
    "Get to the left side of the return sign in SMC1",
    "Reach the top SMC1 end sign without touching any sharpeners and without taking damage",
    "Get all 8 1ups in SMC",
    "Beat SMC screen 2 without using red rings",
    "Get all CP cages in reverse order",
    "Complete CP1 whilst collecting 12 tings or less",
    "Max% and Damageless Crystal Palace",
    "Beat the CP Magician under 20 seconds",
    "Get all 7 1ups in EAJ",
    "Get hit by all Fish on EaJ screen 5 without dying",
    "Get all tings, 1ups & powerups on EaJ screen 1 without taking damage",
    "Kill all enemies on EaJ screen 2 without taking damage",
    "Beat Skops (final screen) without using punch",
    "Beat Skops screen 1 without standing on a surface apart from the start and 3 red platforms",
    "In Skops, get from the photographer to the end sign while only using 1 punch",
    "Take the Skops photographer, then get all cages in reverse order without leaving the screen"
]
