bingoGenerator = require("./generators/generator_bases/srl_generator_v5.js");

var bingoList = [];
bingoList[1] = [
	{name: "400 Rings in Sonic Emerald Coast", types: ["1", "sonic", "rings", "emeraldcoast"]},
	{name: "Drown to death in Sonic Emerald Coast", types: ["1", "sonic", "death", "emeraldcoast"]},
	{name: "Collect 6 unique lives in Sonic Emerald Coast & finish", types: ["1", "sonic", "capsules", "emeraldcoast"]},
	{name: "Break 18 unique capsules in Sonic Emerald Coast", types: ["1", "sonic", "capsules", "emeraldcoast"]},
	{name: "Sonic Emerald Coast Mission A", types: ["1", "sonic", "abc", "emeraldcoast"]},
	{name: "Finish Sonic Emerald Coast via 7 checkpoints", types: ["1", "sonic", "checkpoints", "emeraldcoast"]},
	{name: "Kill 12 Kikis in Sonic Emerald Coast", types: ["1", "sonic", "enemies", "emeraldcoast"]},
	{name: "Complete Sonic Windy Valley w/o spindashing", types: ["1", "sonic", "restricted", "windyvalley"]},
	{name: "Game over to a spike ball in Sonic Windy Valley", types: ["1", "sonic", "death", "windyvalley"]},
	{name: "Trigger 3 Tikal Orbs in Sonic Windy Valley", types: ["1", "sonic", "tikal", "windyvalley"]},
	{name: "Finish Sonic Windy Valley via 5 checkpoints", types: ["1", "sonic", "checkpoints", "windyvalley"]},
	{name: "Kill 2 boa-boa in Sonic Windy Valley", types: ["1", "sonic", "enemies", "windyvalley"]},
	{name: "Sonic Windy Valley Mission A", types: ["1", "sonic", "abc", "windyvalley"]},
	{name: "Break 12 unique capsules in Sonic Windy Valley", types: ["1", "sonic", "capsules", "windyvalley"]},
	{name: "200 Rings in Sonic Windy Valley", types: ["1", "sonic", "rings", "windyvalley"]},
	{name: "Finish taking a shower in Casinopolis with Sonic", types: ["1", "sonic", "funny", "casinopolis"]},
	{name: "Deposit 400 rings in the Casinopolis vault", types: ["1", "rings", "casinopolis"]},
	{name: "Break 4 power-up capsules in Sonic Casinopolis & finish", types: ["1", "sonic", "capsules", "casinopolis"]},
	{name: "Game over to a spike ball in Sonic Casinopolis", types: ["1", "sonic", "death", "casinopolis"]},
	{name: "Kill 6 spinners in Sonic Casinopolis", types: ["1", "sonic", "enemies", "casinopolis"]},
	{name: "Earn 250 rings in a single round of pinball in Casinopolis", types: ["1", "rings", "casinopolis"]},
	{name: "Sonic Casinopolis Mission A", types: ["1", "sonic", "abc", "casinopolis"]},
	{name: "Break 6 speed shoes capsules in Sonic Speed Highway & finish", types: ["1", "sonic", "capsules", "speedhighway"]},
	{name: "Break 20 capsules in Sonic Speed Highway", types: ["1", "sonic", "capsules", "speedhighway"]},
	{name: "Hit the bell in Sonic Speed Highway", types: ["1", "sonic", "funny", "speedhighway"]},
	{name: "Ride the helicopter in Sonic Speed Highway", types: ["1", "sonic", "funny", "speedhighway"]},
	{name: "Kill 14 police carts in Sonic Speed Highway", types: ["1", "sonic", "enemies", "speedhighway"]},
	{name: "Kill 15 spinners in Sonic Speed Highway", types: ["1", "sonic", "enemies", "speedhighway"]},
	{name: "Game over by getting hit with the yellow bunny van in Sonic Speed Highway", types: ["1", "sonic", "death", "speedhighway"]},
	{name: "Game over to a spike ball in Sonic Speed Highway", types: ["1", "sonic", "death", "speedhighway"]},
	{name: "250 Rings in Sonic Speed Highway", types: ["1", "sonic", "rings", "speedhighway"]},
	{name: "Sonic Speed Highway Mission A", types: ["1", "sonic", "abc", "speedhighway"]},
];
bingoList[2] = [
	{name: "Enter the (Sonic) Crystal Ring upgrade room as Tails", types: ["1", "tails", "upgrade", "hub"]},
	{name: "Release 10 animals into the Chao Garden as Tails", types: ["1", "tails", "chao"]},
	{name: "Lose a race to Sonic as Tails", types: ["1", "tails", "death"]},
	{name: "Break 3 unique speed shoes capsules in Tails Windy Valley", types: ["1", "tails", "capsules", "windyvalley"]},
	{name: "Break 10 capsules in Tails Windy Valley", types: ["1", "tails", "capsules", "windyvalley"]},
	{name: "Finish Tails Windy Valley via 2 checkpoints", types: ["1", "tails", "checkpoints", "windyvalley"]},
	{name: "Game over to a spike ball in Tails Windy Valley", types: ["1", "tails", "death", "windyvalley"]},
	{name: "Finish Tails Windy Valley w/o Flying", types: ["1", "tails", "restricted", "windyvalley"]},
	{name: "Tails Windy Valley Mission A", types: ["1", "tails", "abc", "windyvalley"]},
	{name: "100 Rings in Tails Windy Valley", types: ["1", "tails", "rings", "windyvalley"]},
];
bingoList[3] = [
	{name: "Release a penguin into the Chao Garden", types: ["1", "chao"]},
	{name: "Release a seal into the Chao Garden", types: ["1", "chao"]},
	{name: "Release a sea otter into the Chao Garden", types: ["1", "chao"]},
	{name: "Release a parrot into the Chao Garden", types: ["1", "chao"]},
	{name: "Release a rabbit into the Chao Garden", types: ["1", "chao"]},
	{name: "Release a peacock into the Chao Garden", types: ["1", "chao"]},
	{name: "Release a gorilla into the Chao Garden", types: ["1", "chao"]},
	{name: "Release a kangaroo into the Chao Garden", types: ["1", "chao"]},
	{name: "Release a mole into the Chao Garden", types: ["1", "chao"]},
	{name: "Release a elephant into the Chao Garden", types: ["1", "chao"]},
	{name: "Release a robin into the Chao Garden", types: ["1", "chao"]},
	{name: "Release a koala into the Chao Garden", types: ["1", "chao"]},
	{name: "Release a lion into the Chao Garden", types: ["1", "chao"]},
	{name: "Release 50 animals into the Chao Garden", types: ["1", "chao"]},
	{name: "Visit any Chao Garden", types: ["1", "chao"]},
	{name: "Die on any Chao Garden ", types: ["1", "chao", "death"]},
	{name: "Purchase a round & square fruit in the black market", types: ["1", "chao"]},
	{name: "Purchase a sqaure & triangle fruit in the black market", types: ["1", "chao"]},
	{name: "Purchase a triangle & round fruit in the black market", types: ["1", "chao"]},
	{name: "Purchase a heart fruit in the black market", types: ["1", "chao"]},
	{name: "Purchase a hero fruit in the black market", types: ["1", "chao"]},
	{name: "Purchase a dark fruit in the black market", types: ["1", "chao"]},
	{name: "Purchase a chao fruit in the black market", types: ["1", "chao"]},
];
bingoList[4] = [
	{name: "Stop traffic until 6 cars are bumper to bumper", types: ["1", "funny", "hub"]},
	{name: "Climb to the very top of Lost World temple in the Mystic Ruins", types: ["1", "hub"]},
	{name: "Kill an enemy using a Kiki bomb after picking it up", types: ["1", "enemies"]},
	{name: "Visit Big's House", types: ["1", "hub"]},
	{name: "Get 10 unique 1-up capsules", types: ["1", "capsules"]},
	{name: "Reach 10 lives", types: ["1", "capsules"]},
	{name: "Make the game crash while in the story", types: ["1", "funny"]},
	{name: "Read 15 different monitors in Hub as any character", types: ["1"]},
	{name: "Get 4 Emblems in Station Square", types: ["1", "emblems", "hub"]},
];
bingoList[5] = [
	{name: "Kill the Sweeper in Emerald Coast using the Light Speed Attack as Sonic", types: ["2", "sonic", "enemies", "emeraldcoast"]},
	{name: "Ride the snowboard to the bottom of Ice Cap as Sonic", types: ["2", "sonic", "icecap"]},
	{name: "Hit the switch to drop the bridge in act 2 of Sonic Ice Cap", types: ["2", "sonic", "icecap"]},
	{name: "Break 5 capsules in Sonic Ice Cap", types: ["2", "sonic", "capsules", "icecap"]},
	{name: "Kill 3 Ice Balls in Sonic Ice Cap", types: ["2", "sonic", "enemies", "icecap"]},
	{name: "Trigger 3 Tikal Orbs in Sonic Ice Cap", types: ["2", "sonic", "tikal", "icecap"]},
	{name: "200 Rings in Sonic Ice Cap", types: ["2", "sonic", "rings", "icecap"]},
	{name: "Sonic Ice Cap Mission A", types: ["2", "sonic", "abc", "icecap"]},
	{name: "Sonic Twinkle Park Mission A", types: ["2", "sonic", "abc", "twinklepark"]},
	{name: "Drown to death in Sonic Twinkle Park", types: ["2", "sonic", "death", "twinklepark"]},
	{name: "Finish Sonic Twinkle Park via 3 checkpoints", types: ["2", "sonic", "checkpoints", "twinklepark"]},
	{name: "Break 25 unique capsules in Sonic Twinkle Park", types: ["2", "sonic", "capsules", "twinklepark"]},
	{name: "Kill 4 Buyoons in Sonic Twinkle Park", types: ["2", "sonic", "enemies", "twinklepark"]},
	{name: "Kill 20 Kikis in Sonic Twinkle Park", types: ["2", "sonic", "enemies", "twinklepark"]},
	{name: "Bowl a strike in Sonic Twinkle Park", types: ["2", "sonic", "funny", "twinklepark"]},
	{name: "Complete Act 1 of Sonic Twinkle Park using the pink cart", types: ["2", "sonic", "twinklepark"]},
	{name: "Complete Act 1 of Sonic Twinkle Park using the green cart", types: ["2", "sonic", "twinklepark"]},
	{name: "Complete Act 1 of Sonic Twinkle Park using the orange cart", types: ["2", "sonic", "twinklepark"]},
	{name: "Kill every cart driver at the start of Sonic Twinkle Park", types: ["2", "sonic", "enemies", "twinklepark"]},
	{name: "200 Rings in Sonic Twinkle Park", types: ["2", "sonic", "rings", "twinklepark"]},
	{name: "Game over in Act 3 snowboarding section of Ice Cap as Sonic", types: ["2", "sonic", "death", "icecap"]},
];
bingoList[6] = [
	{name: "200 Rings in Tails Casinopolis", types: ["2", "tails", "rings", "casinopolis"]},
	{name: "Complete Tails Casinopolis w/o flying", types: ["2", "tails", "casinopolis"]},
	{name: "Game over to a spike ball in Tails Casinopolis", types: ["2", "tails", "death", "casinopolis"]},
	{name: "Break 15 capsules in Tails Casinopolis", types: ["2", "tails", "capsules", "casinopolis"]},
	{name: "Tails Casinopolis Mission A", types: ["2", "tails", "abc", "casinopolis"]},
	{name: "Score 3000 in Tails Ice Cap", types: ["2", "tails", "score", "icecap"]},
	{name: "Go through 30 posts in Tails Ice Cap", types: ["2", "tails", "icecap"]},
	{name: "Finish Tails Ice Cap w/o touching any ramps", types: ["2", "tails", "icecap"]},
	{name: "100 Rings in Tails Ice Cap", types: ["2", "tails", "rings", "icecap"]},
	{name: "Game over in Tails Ice Cap", types: ["2", "tails", "death", "icecap"]},
	{name: "Tails Ice Cap Mission A", types: ["2", "tails", "abc", "icecap"]},
	{name: "Get the blue balls attack on Chaos 4 as Tails", types: ["2", "tails", "boss"]},
	{name: "Hatch the Golden Egg with Tails", types: ["2", "tails", "chao"]},
	{name: "Touch all 7 chaos emeralds in the past as Tails", types: ["2", "tails", "funny", "past"]},
	{name: "Tails Speed Highway Mission A", types: ["2", "tails", "abc", "speedhighway"]},
	{name: "Complete Tails Speed Highway with a green shield", types: ["2", "tails", "capsules", "speedhighway"]},
	{name: "Break 14 capsules in Speed Highway as Tails", types: ["2", "tails", "capsules", "speedhighway"]},
	{name: "Kill 12 police carts in Speed Highway as Tails", types: ["2", "tails", "enemies", "speedhighway"]},
	{name: "150 Rings in Tails Speed Highway", types: ["2", "tails", "rings", "speedhighway"]},
	{name: "Lose to Eggman in Tails Speed Highway", types: ["2", "tails", "death", "speedhighway"]},
	{name: "Finish Tails Speed Highway via 3 checkpoints", types: ["2", "tails", "checkpoints", "speedhighway"]},
	{name: "Hit the big bell in Speed Highway as Tails", types: ["2", "tails", "funny", "speedhighway"]},
];
bingoList[7] = [
	{name: "Release 10 animals into the Chao Garden as Knuckles", types: ["2", "knuckles", "chao"]},
	{name: "Watch the entire Angel Island Falling cutscene as Knuckles", types: ["2", "knuckles"]},
	{name: "150 Rings in Knuckles Speed Highway", types: ["2", "knuckles", "rings", "speedhighway"]},
	{name: "Break 18 containers in Knuckles Speed Highway", types: ["2", "knuckles", "speedhighway"]},
	{name: "Trigger 12 Tikal orbs in Knuckles Speed Highway", types: ["2", "knuckles", "tikal", "speedhighway"]},
	{name: "Hit the big bell in Knuckles Speed Highway", types: ["2", "knuckles", "funny", "speedhighway"]},
	{name: "Break 9 billboards in Knuckles Speed Highway", types: ["2", "knuckles", "speedhighway"]},
	{name: "Break 7 capsules in Knuckles Speed Highway", types: ["2", "knuckles", "capsules", "speedhighway"]},
	{name: "Kill 9 police carts in Knuckles Speed Highway", types: ["2", "knuckles", "enemies", "speedhighway"]},
	{name: "Knuckles Speed Highway Mission A", types: ["2", "knuckles", "abc", "speedhighway"]},
	{name: "Enter the (Sonic) Crystal Ring upgrade room as Knuckles", types: ["2", "knuckles", "upgrade", "hub"]},
	{name: "Finish taking a shower in Casinopolis as Knuckles", types: ["2", "knuckles", "funny", "casinopolis"]},
	{name: "Break the Golden Sonic Statue in Knuckles Casinopolis", types: ["2", "knuckles", "casinopolis"]},
	{name: "Game over to a pirate in Knuckles Casinopolis", types: ["2", "knuckles", "death", "casinopolis"]},
	{name: "Trigger 7 Tikal orbs in Knuckles Casinopolis", types: ["2", "knuckles", "tikal", "casinopolis"]},
	{name: "Knuckles Casinopolis Mission A", types: ["2", "knuckles", "abc", "casinopolis"]},
	{name: "Break 11 capsules in Knuckles Casinopolis", types: ["2", "knuckles", "capsules", "casinopolis"]},
	{name: "150 Rings in Knuckles Casinopolis", types: ["2", "knuckles", "rings", "casinopolis"]},
	{name: "Kill 23 enemies in Knuckles Casinopolis", types: ["2", "knuckles", "enemies", "casinopolis"]},
	{name: "Kill 6 pirates in Knuckles Casinopolis", types: ["2", "knuckles", "enemies", "casinopolis"]},
	{name: "Defeat Chaos 2 without gliding as Knuckles", types: ["2", "knuckles", "restricted", "boss"]},
	{name: "Drown in the hotel pool at night as Knuckles", types: ["2", "knuckles", "death", "hub"]},
	{name: "Dig up a capsule with Knuckles ", types: ["2", "knuckles", "capsules"]},
	{name: "Dig up a ring pit as Knuckles", types: ["2", "knuckles", "rings"]},
	{name: "Hatch the Golden Egg with Knuckles", types: ["2", "knuckles", "chao"]},
	{name: "Game over to a Kiki Bomb as Knuckles", types: ["2", "knuckles", "death"]},
	{name: "Kill 11 spinners in Knuckles Red Mountain", types: ["2", "knuckles", "enemies", "redmountain"]},
	{name: "Game over to lava in Knuckles Red Mountain", types: ["2", "knuckles", "death", "redmountain"]},
	{name: "Break 20 capsules in Knuckles Red Mountain", types: ["2", "knuckles", "capsules", "redmountain"]},
	{name: "Obtain 6 lives in Knuckles Red Mountain w/o resetting", types: ["2", "knuckles", "capsules", "redmountain"]},
	{name: "Trigger 18 Tikal orbs in Knuckles Red Mountain", types: ["2", "knuckles", "tikal", "redmountain"]},
	{name: "Climb to the very top of Knuckles Red Mountain starting from the very bottom", types: ["2", "knuckles", "funny", "redmountain"]},
	{name: "200 Rings in Knuckles Red Mountain", types: ["2", "knuckles", "rings", "redmountain"]},
	{name: "Knuckles Red Mountain Mission A", types: ["2", "knuckles", "abc", "redmountain"]},
];
bingoList[8] = [
	{name: "Win a chao race", types: ["2", "chao"]},
	{name: "Name the Chao from the Dark Egg after your opponent", types: ["2", "chao"]},
	{name: "Visit all 3 chao gardens", types: ["2", "chao"]},
	{name: "Purchase a round, square & triangle fruit in the black market", types: ["2", "chao"]},
	{name: "Purchase a heart fruit in the black market", types: ["2", "chao"]},
	{name: "Purchase a mushroom in the black market", types: ["2", "chao"]},
	{name: "Visit Eggman's secret bedroom in the Egg Carrier", types: ["2", "hub"]},
	{name: "Get 6 hub emblems", types: ["2", "emblems", "hub"]},
	{name: "20 Emblems", types: ["2", "emblems"]},
	{name: "Reach 15 lives", types: ["2", "capsules"]},
	{name: "Reach 20 lives", types: ["2", "capsules"]},
	{name: "Speak with 5 echidna who are standing still in the past", types: ["2", "past"]},
	{name: "Ride the monorail on the Egg Carrier", types: ["2", "hub"]},
	{name: "Softlock the file with any story progression", types: ["2", "funny"]},
	{name: "Beat Knuckles with Sonic and Sonic with Knuckles (Team Combined)", types: ["2", "team"]},
	{name: "Jump off of 3 Ramps while on a snowboard", types: ["2"]},
	{name: "Climb to the top of the Lost World temple in the past", types: ["2", "past"]},
	{name: "Beat Chaos 4 while holding 4 Rings", types: ["2", "rings", "boss"]},
	{name: "Get a Speed Shoes Capsule with 3 different characters", types: ["2", "capsules"]},
	{name: "Get an Invincibility Capsule with 3 different characters", types: ["2", "capsules"]},
	{name: "Get a Green Shield Capsule with 3 different characters", types: ["2", "capsules"]},
	{name: "Get a Magnet Shield Capsule with 3 different characters", types: ["2", "capsules"]},
];
bingoList[9] = [
	{name: "Game over in the merry-go-round in Sonic Twinkle Park", types: ["3", "sonic", "death", "twinklepark"]},
	{name: "Bring the employee ID card inside the burger shop as Sonic", types: ["3", "sonic", "funny", "hub"]},
	{name: "Complete Sonic Red Mountain w/o spindashing", types: ["3", "sonic", "restricted", "redmountain"]},
	{name: "200 Rings in Sonic Red Mountain", types: ["3", "sonic", "rings", "redmountain"]},
	{name: "Game over to lava in Sonic Red Mountain", types: ["3", "sonic", "death", "redmountain"]},
	{name: "Finish Sonic Red Mountain via 8 checkpoints", types: ["3", "sonic", "checkpoints", "redmountain"]},
	{name: "Kill 14 Kikis in Sonic Red Mountain", types: ["3", "sonic", "enemies", "redmountain"]},
	{name: "Break 22 capsules in Sonic Red Mountain", types: ["3", "sonic", "capsules", "redmountain"]},
	{name: "Sonic Red Mountain Mission A", types: ["3", "sonic", "abc", "redmountain"]},
	{name: "Game over to Sonic as Knuckles", types: ["3", "knuckles", "death", "boss"]},
	{name: "Get the blue balls attack on Chaos 4 as Knuckles", types: ["3", "knuckles", "death", "boss"]},
	{name: "Knuckles Fighting Gloves", types: ["3", "knuckles", "upgrade", "hub"]},
	{name: "100 Rings in Knuckles Lost World", types: ["3", "knuckles", "rings", "lostworld"]},
	{name: "Knuckles Lost World Mission A", types: ["3", "knuckles", "abc", "lostworld"]},
	{name: "Collect 3 emerald pieces in Knuckles Lost World", types: ["3", "knuckles", "restricted", "lostworld"]},
	{name: "Break the bomb capsule in Knuckles Lost World", types: ["3", "knuckles", "capsules", "lostworld"]},
	{name: "Trigger 4 Tikal orbs in Knuckles Lost World", types: ["3", "knuckles", "tikal", "lostworld"]},
	{name: "Break 40 boxes in Knuckles Lost World", types: ["3", "knuckles", "lostworld"]},
	{name: "Break 6 capsules in Knuckles Lost World", types: ["3", "knuckles", "capsules", "lostworld"]},
	{name: "Kill 7 enemies in Knuckles  Lost World", types: ["3", "knuckles", "enemies", "lostworld"]},
];
bingoList[10] = [
	{name: "Release 10 animals into the Chao Garden as Amy", types: ["3", "amy", "chao"]},
	{name: "Make smoke rise out of Zero as Amy ", types: ["3", "amy", "funny"]},
	{name: "Game over to Zero as Amy", types: ["3", "amy", "death"]},
	{name: "Drown to death in Amy Twinkle Park", types: ["3", "amy", "death", "twinklepark"]},
	{name: "Finish Amy Twinkle Park via 2 checkpoints", types: ["3", "amy", "checkpoints", "twinklepark"]},
	{name: "Amy Twinkle Park Mission A", types: ["3", "amy", "abc", "twinklepark"]},
	{name: "Hide in a barrel and confuse Zero in Amy Twinkle Park", types: ["3", "amy", "funny", "twinklepark"]},
	{name: "Trigger 3 Tikal orbs in Amy Twinkle Park", types: ["3", "amy", "tikal", "twinklepark"]},
	{name: "Break 7 capsules in Amy Twinkle Park", types: ["3", "amy", "capsules", "twinklepark"]},
	{name: "Complete Amy Twinkle Park w/o using the Hammer", types: ["3", "amy", "restricted", "twinklepark"]},
	{name: "Destroy 40 explosive barrels in Amy Twinkle Park & finish", types: ["3", "amy", "twinklepark"]},
	{name: "100 Rings in Amy Twinkle Park", types: ["3", "amy", "rings", "twinklepark"]},
	{name: "Climb to the top of the rocket in the Egg Carrier chao garden as Amy", types: ["3", "amy", "chao"]},
	{name: "Amy's Long Green Hammer", types: ["3", "amy", "upgrade"]},
	{name: "Hit 4 buttons in Amy Hot Shelter", types: ["3", "amy", "hotshelter"]},
	{name: "Open 9 bathroom stalls in Amy Hot Shelter", types: ["3", "amy", "hotshelter"]},
	{name: "Trigger 7 Tikal orbs in Amy Hot Shelter", types: ["3", "amy", "tikal", "hotshelter"]},
	{name: "Fix the staircase in Amy Hot Shelter", types: ["3", "amy", "hotshelter"]},
	{name: "Complete Amy Hot Shelter in Autocam", types: ["3", "amy", "restricted", "hotshelter"]},
	{name: "200 Rings in Amy Hot Shelter", types: ["3", "amy", "rings", "hotshelter"]},
	{name: "Amy Hot Shelter Mission A", types: ["3", "amy", "abc", "hotshelter"]},
	{name: "Break 5 Green Shield Capsules in Amy Hot Shelter", types: ["3", "amy", "capsules", "hotshelter"]},
	{name: "Break 3 Invincibility Capsules in Amy Hot Shelter", types: ["3", "amy", "capsules", "hotshelter"]},
	{name: "Break 4 Speed Shoes Capsules in Amy Hot Shelter", types: ["3", "amy", "capsules", "hotshelter"]},
	{name: "Solve both puzzles in Amy Hot Shelter", types: ["3", "amy", "restricted", "hotshelter"]},
	{name: "Die to drowning in Amy Hot Shelter", types: ["3", "amy", "death", "hotshelter"]},
	{name: "Kill 25 Kikis in Amy Hot Shelter", types: ["3", "amy", "enemies", "hotshelter"]},
	{name: "Complete Amy Hot Shelter without using the Hammer", types: ["3", "amy", "restricted", "hotshelter"]},
	{name: "Release 10 animals into the Chao Garden as Gamma", types: ["3", "gamma", "chao"]},
	{name: "Game over to a Kiki Bomb as Gamma", types: ["3", "gamma", "death"]},
	{name: "Kill ONLY 17 Knuckles dolls before Sonic doll in Gamma Final Egg", types: ["3", "gamma", "restricted", "finalegg"]},
	{name: "Kill ONLY 21 Tails dolls before Sonic doll in Gamma Final Egg", types: ["3", "gamma", "restricted", "finalegg"]},
	{name: "Break 10 capsules in Gamma Final Egg", types: ["3", "gamma", "capsules", "finalegg"]},
	{name: "100 Rings in Gamma Final Egg", types: ["3", "gamma", "rings", "finalegg"]},
	{name: "Gamma Final Egg Mission A", types: ["3", "gamma", "abc", "finalegg"]},
	{name: "Enter the Sonic crystal ring room as Gamma", types: ["3", "gamma", "upgrade"]},
	{name: "Speak to the clerk in the burger shop as Gamma", types: ["3", "gamma", "funny"]},
	{name: "Complete Gamma Emerald Coast w/o shooting", types: ["3", "gamma", "restricted", "emeraldcoast"]},
	{name: "Break 8 capsules in Gamma Emerald Coast", types: ["3", "gamma", "capsules", "emeraldcoast"]},
	{name: "Game over to the rhinotank in Gamma Emerald Coast", types: ["3", "gamma", "death", "emeraldcoast"]},
	{name: "Destroy umbrellas, tables & chairs in Gamma Emerald Coast", types: ["3", "gamma", "emeraldcoast"]},
	{name: "130 Rings in Gamma Emerald Coast", types: ["3", "gamma", "rings", "emeraldcoast"]},
	{name: "Gamma Emerald Coast Mission A", types: ["3", "gamma", "abc", "emeraldcoast"]},
];
bingoList[11] = [
	{name: "Release 10 animals into the Chao Garden as Big", types: ["3", "big", "chao"]},
	{name: "Catch a shark as Big", types: ["3", "big"]},
	{name: "50 Rings in Big Twinkle Park", types: ["3", "big", "rings", "twinklepark"]},
	{name: "Drown to death in Big Twinkle Park", types: ["3", "big", "death", "twinklepark"]},
	{name: "Kill 4 Kikis in Big Twinkle Park", types: ["3", "big", "enemies", "twinklepark"]},
	{name: "Break 2 capsules in Big Twinkle Park", types: ["3", "big", "capsules", "twinklepark"]},
	{name: "Catch the Mecha Fish in Big Twinkle Park", types: ["3", "big", "twinklepark"]},
	{name: "Big Twinkle Park Mission A", types: ["3", "big", "abc", "twinklepark"]},
	{name: "100 Rings in Big Ice Cap", types: ["3", "big", "rings", "icecap"]},
	{name: "Break 9 capsules in Big Ice Cap", types: ["3", "big", "capsules", "icecap"]},
	{name: "Catch 3 fish in Big Twinkle Park before Froggy", types: ["3", "big", "twinklepark"]},
	{name: "Drown to death in Ice Cap as Big", types: ["3", "big", "death", "icecap"]},
	{name: "Catch the Mecha Fish in Big Ice Cap", types: ["3", "big", "icecap"]},
	{name: "Big Ice Cap Mission A", types: ["3", "big", "abc", "icecap"]},
	{name: "Drown to death in Big Emerald Coast", types: ["3", "big", "death", "emeraldcoast"]},
	{name: "Go to the Master Emerald with Big", types: ["3", "big"]},
	{name: "Hatch the Golden Egg with Big", types: ["3", "big", "chao"]},
];
bingoList[12] = [
	{name: "Release a skunk into the Chao Garden", types: ["3", "chao"]},
	{name: "25 Emblems", types: ["3", "emblems"]},
	{name: "Reach 25 lives", types: ["3", "capsules"]},
	{name: "Visit a Chao Garden with 3 different characters", types: ["3", "chao"]},
	{name: "Get 4 emblems in the Mystic Ruins", types: ["3", "emblems", "hub"]},
];
bingoList[13] = [
	{name: "Finish Sonic Sky Deck via 9 checkpoints", types: ["4", "sonic", "checkpoints", "skydeck"]},
	{name: "Kill 100 cannons in Sonic Sky Deck", types: ["4", "sonic", "enemies", "skydeck"]},
	{name: "Kill 20 flying enemies in Sonic Sky Deck", types: ["4", "sonic", "enemies", "skydeck"]},
	{name: "200 Rings in Sonic Sky Deck", types: ["4", "sonic", "rings", "skydeck"]},
	{name: "Destroy a jet on Sonic Sky Deck", types: ["4", "sonic", "enemies", "skydeck"]},
	{name: "Break 30 capsules in Sonic Sky Deck", types: ["4", "sonic", "capsules", "skydeck"]},
	{name: "Sonic Sky Deck Mission A", types: ["4", "sonic", "abc", "skydeck"]},
	{name: "Game over by being eaten by Chaos 6 as Sonic", types: ["4", "sonic", "death", "boss"]},
	{name: "Beat Chaos 6 without picking up any Ice Balls as Sonic", types: ["4", "sonic", "restricted", "boss"]},
	{name: "Activate 5 mirrors in Sonic Lost World", types: ["4", "sonic", "restricted", "lostworld"]},
	{name: "Break 20 capsules in Sonic Lost World", types: ["4", "sonic", "capsules", "lostworld"]},
	{name: "Go thru the fire tunnel ringless in Sonic Lost World", types: ["4", "sonic", "ringless", "lostworld"]},
	{name: "Break 15 boxes in Sonic Lost World", types: ["4", "sonic", "lostworld"]},
	{name: "Trigger 4 Tikal Orbs in Sonic Lost World", types: ["4", "sonic", "tikal", "lostworld"]},
	{name: "Complete Sonic Lost World w/o spindashing, except for light speed attack", types: ["4", "sonic", "restricted", "lostworld"]},
	{name: "Kill 9 enemies in Sonic Lost World", types: ["4", "sonic", "enemies", "lostworld"]},
	{name: "Press all 6 buttons around the snake in Sonic Lost World", types: ["4", "sonic", "restricted", "lostworld"]},
	{name: "Game over to the boulder in Sonic Lost World", types: ["4", "sonic", "death", "lostworld"]},
	{name: "Sonic Lost World Mission A", types: ["4", "sonic", "abc", "lostworld"]},
	{name: "Complete Tails Sky Deck w/o Flying", types: ["4", "tails", "restricted", "skydeck"]},
	{name: "Break 30 capsules in Tails Sky Deck", types: ["4", "tails", "capsules", "skydeck"]},
	{name: "Game over to the big cannon in Tails Sky Deck", types: ["4", "tails", "death", "skydeck"]},
	{name: "Kill 8 spinners in Tails Sky Deck", types: ["4", "tails", "enemies", "skydeck"]},
	{name: "Get 5 lives in Tails Sky Deck & finish", types: ["4", "tails", "capsules", "skydeck"]},
	{name: "Break 3 Invincibility capsules in Tails Sky Deck & finish", types: ["4", "tails", "capsules", "skydeck"]},
	{name: "150 Rings in Tails Sky Deck", types: ["4", "tails", "rings", "skydeck"]},
	{name: "Tails Sky Deck Mission A", types: ["4", "tails", "abc", "skydeck"]},
	{name: "Game over to Gamma as Tails", types: ["4", "tails", "death", "boss"]},
	{name: "Kill 20 cannons in Knuckles  Sky Deck", types: ["4", "knuckles", "enemies", "skydeck"]},
	{name: "Kill 16 spinners in Knuckles Sky Deck", types: ["4", "knuckles", "enemies", "skydeck"]},
	{name: "Game over from falling to death in Knuckles Sky Deck", types: ["4", "knuckles", "death", "skydeck"]},
	{name: "Trigger 3 Tikal orbs in Knuckles Sky Deck", types: ["4", "knuckles", "tikal", "skydeck"]},
	{name: "Tilt the ship 4 ways in Knuckles Sky Deck", types: ["4", "knuckles", "funny", "skydeck"]},
	{name: "100 Rings in Knuckles Sky Deck", types: ["4", "knuckles", "rings", "skydeck"]},
	{name: "Break 10 capsules in Knuckles Sky Deck", types: ["4", "knuckles", "capsules", "skydeck"]},
	{name: "Kill 20 cannons in Knuckles Sky Deck", types: ["4", "knuckles", "enemies", "skydeck"]},
	{name: "Knuckles Sky Deck Mission A", types: ["4", "knuckles", "abc", "skydeck"]},
];
bingoList[14] = [
	{name: "Get to the very top of Tails workshop as Amy", types: ["4", "amy", "funny", "hub"]},
	{name: "Stand where Gamma story begins as Amy", types: ["4", "amy", "funny", "hub"]},
	{name: "Hatch the Golden Egg with Amy", types: ["4", "amy", "chao"]},
	{name: "80 Rings without ? capsules in Amy Final Egg", types: ["4", "amy", "rings", "finalegg"]},
	{name: "Hide in a barrel and make Zero confused in Amy Hot Shelter", types: ["4", "amy", "funny", "finalegg"]},
	{name: "Trigger 3 Tikal orbs in Amy Final Egg", types: ["4", "amy", "tikal", "finalegg"]},
	{name: "Game over from falling in Amy Final Egg", types: ["4", "amy", "death", "finalegg"]},
	{name: "Break 7 capsules in Amy Final Egg", types: ["4", "amy", "capsules", "finalegg"]},
	{name: "Kill 5 spinners in Amy Final Egg", types: ["4", "amy", "enemies", "finalegg"]},
	{name: "Kill 9 lasers in Amy Final Egg", types: ["4", "amy", "enemies", "finalegg"]},
	{name: "Amy Final Egg Mission A", types: ["4", "amy", "abc", "finalegg"]},
	{name: "Hammer Spin Attack on the top ledge of the Lost World Temple as Amy", types: ["4", "amy", "upgrade", "hub"]},
	{name: "Hammer Spin Attack at the end of the airstrip by Tails workshop as Amy", types: ["4", "amy", "upgrade", "hub"]},
	{name: "Escape thru the Green Door in Amy Final Egg", types: ["4", "amy", "funny", "finalegg"]},
	{name: "Escape thru the Yellow Door in Amy Final Egg", types: ["4", "amy", "funny", "finalegg"]},
	{name: "Escape thru the Red Door in Amy Final Egg", types: ["4", "amy", "funny", "finalegg"]},
	{name: "Escape thru the Blue Door in Amy Final Egg", types: ["4", "amy", "funny", "finalegg"]},
	{name: "Escape thru the Purple Door in Amy Final Egg", types: ["4", "amy", "funny", "finalegg"]},
	{name: "Ride on top of the elevator in Amy Final Egg", types: ["4", "amy", "finalegg"]},
	{name: "Escape thru the last Door you check in Amy Final Egg", types: ["4", "amy", "funny", "finalegg"]},
];
bingoList[15] = [
	{name: "250 Rings in Gamma Hot Shelter", types: ["4", "gamma", "rings", "hotshelter"]},
	{name: "Gamma Hot Shelter Mission A", types: ["4", "gamma", "abc", "hotshelter"]},
	{name: "Complete the train section of Gamma Hot Shelter w/o dying", types: ["4", "gamma", "restricted", "hotshelter"]},
	{name: "Break 15 capsules in Gamma Hot Shelter", types: ["4", "gamma", "capsules", "hotshelter"]},
	{name: "Kill 50 Kikis in Gamma Hot Shelter", types: ["4", "gamma", "enemies", "hotshelter"]},
	{name: "Game over to E105 Zeta in Gamma Hot Shelter", types: ["4", "gamma", "death", "hotshelter"]},
	{name: "Finish Gamma Hot Shelter via 8 checkpoints", types: ["4", "gamma", "checkpoints", "hotshelter"]},
	{name: "Complete Gamma Hot Shelter w/o hovering", types: ["4", "gamma", "restricted", "hotshelter"]},
	{name: "Game over to Sonic as Gamma", types: ["4", "gamma", "death", "boss"]},
	{name: "Destroy both monkey destruction devices in the Mystic Ruins as Gamma", types: ["4", "gamma", "funny", "hub"]},
	{name: "Hatch the Golden Egg with Gamma", types: ["4", "gamma", "chao"]},
	{name: "Gamma Red Mountain Mission A", types: ["4", "gamma", "abc", "redmountain"]},
	{name: "Finish Gamma Red Mountain via 2 checkpoints", types: ["4", "gamma", "checkpoints", "redmountain"]},
	{name: "Break 10 capsules in Gamma Red Mountain", types: ["4", "gamma", "capsules", "redmountain"]},
	{name: "Game over to E104 Epsilon in Gamma Red Mountain", types: ["4", "gamma", "death", "redmountain"]},
	{name: "Destroy 10 rocks in Gamma Red Mountain", types: ["4", "gamma", "redmountain"]},
	{name: "Kill 40 spinners in Gamma Red Mountain", types: ["4", "gamma", "enemies", "redmountain"]},
	{name: "Kill 14 Kikis in Gamma Red Mountain", types: ["4", "gamma", "enemies", "redmountain"]},
	{name: "150 Rings in Gamma Red Mountain", types: ["4", "gamma", "rings", "redmountain"]},
	{name: "85 Rings in Gamma Windy Valley", types: ["4", "gamma", "rings", "windyvalley"]},
	{name: "Destroy 19 islands in Gamma Windy Valley", types: ["4", "gamma", "windyvalley"]},
	{name: "Game over to E103 Delta in Gamma Windy Valley", types: ["4", "gamma", "death", "windyvalley"]},
	{name: "Die from shooting out the bridge in Gamma Windy Valley", types: ["4", "gamma", "death", "windyvalley"]},
	{name: "Kill 11 enemies in Gamma Windy Valley", types: ["4", "gamma", "enemies", "windyvalley"]},
	{name: "75 Rings in Gamma Windy Valley", types: ["4", "gamma", "rings", "windyvalley"]},
	{name: "Complete Gamma Windy Valley w/o hovering", types: ["4", "gamma", "restricted", "windyvalley"]},
	{name: "Kill E102 Delta from one of the ledges above in Gamma Windy Valley", types: ["4", "gamma", "funny", "windyvalley"]},
	{name: "Gamma Windy Valley Mission A", types: ["4", "gamma", "abc", "windyvalley"]},
	{name: "Gamma Laser Blaster", types: ["4", "gamma", "upgrade", "hub"]},
];
bingoList[16] = [
	{name: "Bring a chao egg to the top of the rocket in the Egg Carrier chao garden", types: ["4", "funny", "chao"]},
	{name: "Big Emerald Coast Mission A", types: ["4", "big", "", "emeraldcoast"]},
	{name: "Kill 3 Kikis in Big Emerald Coast", types: ["4", "big", "", "emeraldcoast"]},
	{name: "92 Rings in Big Emerald Coast", types: ["4", "big", "", "emeraldcoast"]},
	{name: "Catch the Mecha Fish in Big Emerald Coast", types: ["4", "big", "", "emeraldcoast"]},
	{name: "Catch a fish in the hidden island cavern in Big Emerald Coast", types: ["4", "big", "", "emeraldcoast"]},
	{name: "Catch 1 fish in Big Hot Shelter before froggy", types: ["4", "big", "", "hotshelter"]},
	{name: "Drown to death in Big Hot Shelter", types: ["4", "big", "", "hotshelter"]},
	{name: "30 Emblems", types: ["4", "emblems"]},
	{name: "Hatch the Silver, Gold, &  Dark Egg", types: ["4", "funny", "chao"]},
	{name: "Get 4 Emblems in the Egg Carrier", types: ["4", "emblems", "hub"]},
];
bingoList[17] = [
	{name: "Complete Sonic Final Egg w/o spindashing", types: ["5", "sonic", "restricted", "finalegg"]},
	{name: "Sonic Final Egg Mission A", types: ["5", "sonic", "abc", "finalegg"]},
	{name: "Break 35 capsules in Sonic Final Egg", types: ["5", "sonic", "capsules", "finalegg"]},
	{name: "Kill 20 Spinners in Sonic Final Egg", types: ["5", "sonic", "enemies", "finalegg"]},
	{name: "Get 3 speed shoes in Sonic Final Egg & finish", types: ["5", "sonic", "capsules", "finalegg"]},
	{name: "Get to the secret area above the start of Gammas Final Egg as Sonic", types: ["5", "sonic", "funny", "finalegg"]},
	{name: "Destroy a Sonic Doll in Sonic Final Egg", types: ["5", "sonic", "funny", "finalegg"]},
	{name: "Get 3 magnet shields in Sonic Final Egg & finish", types: ["5", "sonic", "capsules", "finalegg"]},
	{name: "Get 11 1up capsules in Sonic Final Egg & finish", types: ["5", "sonic", "capsules", "finalegg"]},
	{name: "Softlock Egg Walker with whistles as Tails", types: ["5", "tails", "funny", "boss"]},
	{name: "Beat MKII Beta w/o jumping as Gamma", types: ["5", "gamma", "restricted", "boss"]},
	{name: "Boss Rush ringless as Gamma", types: ["5", "gamma", "restricted", "boss"]},
	{name: "Break 10 capsules in Big Hot Shelter", types: ["5", "big", "capsules", "hotshelter"]},
	{name: "Big Hot Shelter Mission A", types: ["5", "big", "abc", "hotshelter"]},
	{name: "Unplug the Plug in Big Hot Sheter", types: ["5", "big", "hotshelter"]},
	{name: "Catch Froggy in Chaos 6 as Big", types: ["5", "big", "boss"]},
];
bingoList[18] = [
	{name: "Game over to a Beat in Sonic Final Egg", types: ["5", "sonic", "death", "finalegg"]},
	{name: "250 Rings in Sonic Final Egg", types: ["5", "sonic", "rings", "finalegg"]},
	{name: "Destroy a Tails Doll in Sonic Final Egg", types: ["5", "sonic", "funny", "finalegg"]},
	{name: "Finish Sonic Final Egg via 9 checkpoints", types: ["5", "sonic", "checkpoints", "finalegg"]},
	{name: "Beat Sonic Egg Viper ringless", types: ["5", "sonic", "restricted", "boss"]},
	{name: "Sonic Boss Rush w/o spindashing", types: ["5", "sonic", "restricted", "boss"]},
	{name: "Beat Chaos 6 using the Maximum Heat Attack as Knuckles", types: ["5", "knuckles", "upgrade", "boss"]},
	{name: "Knuckles Boss Rush ringless", types: ["5", "knuckles", "restricted", "boss"]},
	{name: "Beat Zero ringless as Amy", types: ["5", "amy", "restricted", "boss"]},
	{name: "100 Rings in Big Hot Shelter", types: ["5", "big", "rings", "hotshelter"]},
	{name: "Finish Big Hot Shelter via 1 checkpoint", types: ["5", "big", "checkpoints", "hotshelter"]},
	{name: "Kill 5 Kikis in Big Hot Shelter", types: ["5", "big", "enemies", "hotshelter"]},
	{name: "Get 3 of Big's Lure Upgrades", types: ["5", "big", "upgrade"]},
	{name: "Get 4 of Big's Lure Upgrades", types: ["5", "big", "upgrade"]},
];
bingoList[19] = [
	{name: "100% any character story", types: ["5", "mission"]},
	{name: "35 Emblems", types: ["5", "emblems"]},
	{name: "5 Missions in Mission Mode", types: ["5", "mission"]},
	{name: "10 Missions in Mission Mode", types: ["5", "mission"]},
	{name: "Die with every character", types: ["5", "death"]},
	{name: "Get a 1-up Capsule with every character", types: ["5", "capsules"]},
	{name: "Hang out by the empty pool in the Egg Carrier as Amy", types: ["5", "funny", "hub"]},
	{name: "Find Metal Sonic as Sonic", types: ["5", "funny", "hub"]},
];
bingoList[20] = [
	{name: "Beat Gamma with Sonic and Sonic with Gamma (Team Combined)", types: ["5", "team", "boss"]},
	{name: "Hit a big bell in Speed Highway with 3 different characters (Team Combined)", types: ["5", "team", "speedhighway"]},
	{name: "Place all key stones (Ice, Wind, Gold & Silver) (Team Combined)", types: ["5", "team", "restricted", "hub"]},
	{name: "Complete Red Mountain as Sonic, Gamma & Knuckles (Team Combined)", types: ["5", "team", "redmountain"]},
	{name: "Complete Hot Shelter as Amy, Big & Gamma (Team Combined)", types: ["5", "team", "hotshelter"]},
	{name: "Complete Twinkle Park as Sonic, Amy & Big (Team Combined)", types: ["5", "team", "twinklepark"]},
	{name: "Beat Chaos 4 with Sonic, Tails & Knuckles (Team Combined)", types: ["5", "team", "boss"]},
	{name: "Complete Speed Highway with Tails, Sonic & Knuckles (Team Combined)", types: ["5", "team", "speedhighway"]},
	{name: "Game over as every character", types: ["5", "death"]},
	{name: "Trigger Cream's cutscene with every character (Team Combined)", types: ["5", "team", "funny"]},
	{name: "All Upgrades (Team Combined)", types: ["5", "team", "upgrade"]},
];
bingoList[21] = [
	{name: "Get a 25 posts streak in Tails Sand Hill", types: ["2", "tails", "sandhill"]},
	{name: "Beat Twinkle Circuit with any character", types: ["2", "twinklecircuit"]},
	{name: "Score 6000 in Hedgehog Hammer as Amy", types: ["3", "amy"]},
	{name: "Score 5000 in Hedgehog Hammer as Amy", types: ["3", "amy"]},
	{name: "Sky Chase Act 2 Score Emblem (20,000)", types: ["4", "emblems"]},
	{name: "Complete Sand Hill with Sonic", types: ["2", "sonic", "sandhill"]},
	{name: "Complete the Twinkle Circuit with Big", types: ["3", "big", "twinklecircuit"]},
	{name: "Complete Twinkle Circuit with Gamma", types: ["5", "gamma", "twinklecircuit"]},
	{name: "Unlock Gamma w/o entering any Sky Chase", types: ["5", "gamma", "restricted"]},
	{name: "Unlock Amy w/o entering any Sky Chase", types: ["5", "amy", "restricted"]},
	{name: "Complete Sand Hill w/o touching the analog stick", types: ["2", "sandhill", "restricted"]},
];
bingoList[22] = [
	{name: "Collect 4 of a kind in the 2nd table in Casinopolis pinball cards", types: ["casinopolis"]},
	{name: "Fly with Night in Casinopolis pinball cards", types: ["casinopolis"]},
	{name: "Get Final Eggman in Casinopolis pinball slots", types: ["casinopolis"]},
	{name: "Get Both 1up Capsules in Casinopolis pinball slots", types: ["casinopolis"]},
	{name: "Get 3 in a row in Casinopolis pinball slots", types: ["casinopolis"]},
	{name: "Get to the 2nd table in Casinopolis pinball cards", types: ["casinopolis"]},
	{name: "Fly around Night in Casinopolis pinball cards", types: ["casinopolis"]},
];
bingoList[23] = [
	{name: "Mission 4 (Tails, Mystic Ruins)", types: ["tails", "mission"]},
	{name: "Mission 5 (Knuckles, Station Square)", types: ["knuckles", "mission"]},
	{name: "Mission 6 (Amy, Mystic Ruins)", types: ["amy", "mission"]},
	{name: "Mission 7 (Gamma, Mystic Ruins)", types: ["gamma", "mission"]},
	{name: "Mission 8 (Big, Station Square)", types: ["big", "mission"]},
	{name: "Mission 10 (Tails, Station Square)", types: ["tails", "mission"]},
	{name: "Mission 12 (Knuckles, Mystic Ruins)", types: ["knuckles", "mission"]},
	{name: "Mission 14 (Big, Station Square)", types: ["big", "mission"]},
	{name: "Mission 16 (Tails, Mystic Ruins)", types: ["tails", "mission"]},
	{name: "Mission 18 (Amy, Station Square)", types: ["amy", "mission"]},
	{name: "Mission 19 (Amy, Station Square)", types: ["amy", "mission"]},
	{name: "Mission 21 (Gamma, Mystic Ruins)", types: ["gamma", "mission"]},
	{name: "Mission 22 (Big, Station Square)", types: ["big", "mission"]},
	{name: "Mission 24 (Tails, Station Square)", types: ["tails", "mission"]},
	{name: "Mission 25 (Knuckles, Station Square)", types: ["knuckles", "mission"]},
	{name: "Mission 26 (Knuckles, Station Square)", types: ["knuckles", "mission"]},
	{name: "Mission 29 (Big, Station Square)", types: ["big", "mission"]},
	{name: "Mission 31 (Tails, Station Square)", types: ["tails", "mission"]},
	{name: "Mission 32 (Knuckles, Mystic Ruins)", types: ["knuckles", "mission"]},
	{name: "Mission 35 (Big, Mystic Ruins)", types: ["big", "mission"]},
	{name: "Mission 37 (Tails, Mystic Ruins)", types: ["tails", "mission"]},
	{name: "Mission 38 (Knuckles, Mystic Ruins)", types: ["knuckles", "mission"]},
	{name: "Mission 39 (Gamma, Station Square)", types: ["gamma", "mission"]},
	{name: "Mission 42 (Gamma, Egg Carrier)", types: ["gamma", "mission"]},
	{name: "Mission 43 (Amy, Egg Carrier)", types: ["amy", "mission"]},
	{name: "Mission 44 (Big, Egg Carrier)", types: ["big", "mission"]},
	{name: "Mission 47 (Tails, Mystic Ruins)", types: ["tails", "mission"]},
	{name: "Mission 48 (Knuckles, Station Square)", types: ["knuckles", "mission"]},
	{name: "Mission 50 (Amy, Mystic Ruins)", types: ["amy", "mission"]},
	{name: "Mission 51 (Gamma, Mystic Ruins)", types: ["gamma", "mission"]},
	{name: "Mission 52 (Big, Mystic Ruins)", types: ["big", "mission"]},
	{name: "Mission 54 (Tails, Mystic Ruins)", types: ["tails", "mission"]},
	{name: "Mission 56 (Knuckles, Mystic Ruins)", types: ["knuckles", "mission"]},
	{name: "Mission 59 (Knuckles, Egg Carrier)", types: ["knuckles", "mission"]},
	{name: "Mission 60 (Big, Mystic Ruins)", types: ["big", "mission"]},
];
bingoList[24] = [
	{name: "Mission 1 (Sonic, Station Square)", types: ["sonic", "mission"]},
	{name: "Mission 2 (Sonic, Mystic Ruins)", types: ["sonic", "mission"]},
	{name: "Mission 3 (Sonic, Station Square)", types: ["sonic", "mission"]},
	{name: "Mission 9 (Sonic, Station Square)", types: ["sonic", "mission"]},
	{name: "Mission 11 (Sonic, Mystic Ruins)", types: ["sonic", "mission"]},
	{name: "Mission 13 (Sonic, Station Square)", types: ["sonic", "mission"]},
	{name: "Mission 15 (Sonic, Mystic Ruins)", types: ["sonic", "mission"]},
	{name: "Mission 17 (Sonic, Station Square)", types: ["sonic", "mission"]},
	{name: "Mission 20 (Sonic, Mystic Ruins)", types: ["sonic", "mission"]},
	{name: "Mission 23 (Sonic, Station Square)", types: ["sonic", "mission"]},
	{name: "Mission 27 (Sonic, Station Square)", types: ["sonic", "mission"]},
	{name: "Mission 28 (Sonic, Station Square)", types: ["sonic", "mission"]},
	{name: "Mission 30 (Sonic, Mystic Ruins)", types: ["sonic", "mission"]},
	{name: "Mission 33 (Sonic, Egg Carrier)", types: ["sonic", "mission"]},
	{name: "Mission 34 (Sonic, Egg Carrier)", types: ["sonic", "mission"]},
	{name: "Mission 36 (Sonic, Egg Carrier)", types: ["sonic", "mission"]},
	{name: "Mission 40 (Sonic, Mystic Ruins)", types: ["sonic", "mission"]},
	{name: "Mission 41 (Sonic, Mystic Ruins)", types: ["sonic", "mission"]},
	{name: "Mission 45 (Sonic, Mystic Ruins)", types: ["sonic", "mission"]},
	{name: "Mission 46 (Sonic, Mystic Ruins)", types: ["sonic", "mission"]},
	{name: "Mission 49 (Sonic, Station Square)", types: ["sonic", "mission"]},
	{name: "Mission 53 (Sonic, Mystic Ruins)", types: ["sonic", "mission"]},
	{name: "Mission 55 (Sonic, Station Square)", types: ["sonic", "mission"]},
	{name: "Mission 57 (Sonic, Mystic Ruins)", types: ["sonic", "mission"]},
	{name: "Mission 58 (Sonic, Mystic Ruins)", types: ["sonic", "mission"]},
];
bingoList[25] = [
	{name: "80 Emblems (Team Combined)", types: ["emblems", "team"]},
	{name: "1 Chao Emblem", types: ["emblems"]},
	{name: "30 Missions (Team Combined)", types: ["mission", "team"]},
	{name: "5,000 Total Rings", types: ["rings"]},
];
