var bingoList = [];
bingoList[1] = [
    { name: "Any Energizing Meal", types: ["Cooking","Stamina"] },
    { name: "Any Hasty Meal", types: ["Cooking"] },
    { name: "Hasty Elixir", types: ["Cooking"] },
    { name: "Kill an enemy using only Magnesis", types: ["Basic Combat"] },
    { name: "Game Over from Guardian Laser", types: ["game Over"] },
    { name: "Game Over from Ice Water", types: ["Game Over"] },
    { name: "Any Stalfos 'Arm' Equipment item", types: ["Equipment"] },
    { name: "3 Identical Weapons", types: ["Equipment"] },
    { name: "Obtain a 'Boko' Weapon, Bow, and Shield", types: ["Equipment"] },
    { name: "Any Spicy Meal", types: ["Cooking","Cold Resistance"] },
    { name: "Obtain a Purple Rupee", types: ["Rupee"] },
    { name: "Soup Ladle", types: ["Equipment"] },
    { name: "Game Over from Bees", types: ["Game Over"] },
    { name: "Dubious Food", types: ["Cooking"] },
    { name: "Rock-Hard Food", types: ["Cooking"] },
    { name: "Wooden Mop", types: ["Equipment"] },
    { name: "Any 'Lizal' Equipment item", types: ["Equipment"] },
    { name: "Any 'Zora' Equipment item", types: ["Equipment"] },
    { name: "Any Boomerang", types: ["Equipment"] },
    { name: "Farming Hoe", types: ["Equipment"] },
    { name: "3 Great Plateau Koroks", types: ["Korok","Plateau"] },
    { name: "Kill a Decayed Guardian", types: ["Miniboss","Guardian"] }
];
bingoList[2] = [
    { name: "Save a Traveler in Peril", types: ["Basic Combat"] },
    { name: "Fishing Harpoon", types: ["Equipment"] },
    { name: "3 Identical Bows", types: ["Equipment"] },
    { name: "Obtain a Silver Rupee", types: ["Rupee"] },
    { name: "Collect 10 Acorns", types: ["Collector","Misc"] },
    { name: "Kill an enemy using only a Shield", types: ["Basic Combat"] },
    { name: "Sneaky Elixir", types: ["Cooking"] },
    { name: "3 Identical Shields", types: ["Equipment"] },
    { name: "Obtain a Gold Rupee", types: ["Rupee"] },
    { name: "Game Over from Cuccos", types: ["Game Over"] },
    { name: "Any 'Moblin' Equipment item", types: ["Equipment"] },
    { name: "Energizing Elixir", types: ["Cooking","Stamina"] },
    { name: "5 Great Plateau Koroks", types: ["Korok","Plateau"] },
    { name: "5 Koroks", types: ["Korok"] },
    { name: "Kill a (normal) Stone Talus", types: ["Miniboss","Talus","Rupee","Gems"] },
    { name: "Kill a Stone Talus of any kind", types: ["Miniboss","Talus","Rupee","Gems"] },
    { name: "Kill a Blue Hinox", types: ["Miniboss","Hinox"] },
    { name: "Kill a Hinox of any kind", types: ["Miniboss","Hinox"] },
    { name: "Kill a fire-typed Wizzrobe", types: ["Basic Combat","Wizzrobe"] },
    { name: "Kill a Wizzrobe of any kind", types: ["Basic Combat","Wizzrobe"] },
    { name: "Open 2 Bokoblin Camp Chests", types: ["Basic Combat"] },
    { name: "Any Fire-typed Equipment item", types: ["Equipment","Heat Resistance"] },
    { name: "Any Rod Weapon", types: ["Equipment","Wizzrobe","Cold Resistance","Heat Resistance"] }
];
bingoList[3] = [
    { name: "Hearty Elixir", types: ["Cooking"] },
    { name: "3 Central Tower Koroks", types: ["Korok","Central Hyrule"] },
    { name: "Glazed Meat", types: ["Cooking","Stamina"] },
    { name: "Drown an Enemy", types: ["Basic Combat"] },
    { name: "'A Good-Sized Horse' Side Quest", types: ["Side Quest","Wasteland","Mount"] },
    { name: "Any Sneaky Meal", types: ["Cooking"] },
    { name: "Electro Elixir", types: ["Cooking"] },
    { name: "1 Dog Treasure", types: ["Dog Treasure"] },
    { name: "7 Great Plateau Koroks", types: ["Korok","Plateau"] },
    { name: "Kill a Guardian Stalker", types: ["Miniboss","Guardian"] },
    { name: "Register a Horse", types: ["Mount"] },
    { name: "Obtain 20 Fire Arrows", types: ["Equipment"] },
    { name: "Any Electro Meal", types: ["Cooking"] },
    { name: "Spicy Elixir", types: ["Cooking","Cold Resistance"] },
    { name: "Regain 2 Hearts by Eating Rock-Hard Food", types: ["Cooking"] },
    { name: "Anger a Cucco", types: ["Misc"] },
    { name: "Any Tough Meal", types: ["Cooking"] },
    { name: "Visit the Edge of the World", types: ["Misc"] },
    { name: "Any Guardian Spear", types: ["Equipment","Guardian"] },
    { name: "Mount a Deer", types: ["Mount"] },
    { name: "3 Lake Tower Koroks", types: ["Korok","Lake"] },
    { name: "A Minor Test of Strength Shrine", types: ["Shrine","Guardian"] },
    { name: "3 Dueling Peaks Koroks", types: ["Korok","Dueling Peaks"] },
    { name: "Give Beedle a Beetle", types: ["Beedle"] },
    { name: "Activate Central Tower", types: ["Tower","Central Hyrule"] },
    { name: "Mighty Elixir", types: ["Cooking","Basic Combat","Miniboss"] },
    { name: "Any Mighty Meal", types: ["Cooking","Basic Combat","Miniboss"] },
    { name: "Obtain 3 fairies", types: ["Fairy","Great Fairy"] }
];
bingoList[4] = [
    { name: "Obtain a 'Lizal' Weapon, Bow, and Shield", types: ["Equipment"] },
    { name: "Tough Elixir", types: ["Cooking"] },
    { name: "'Watch Out for the Flowers' Shrine Quest", types: ["Shrine","Shrine Quest","Dueling Peaks"] },
    { name: "Collect 20 Bird Eggs", types: ["Collector","Misc"] },
    { name: "Activate Dueling Peaks Tower", types: ["Tower","Dueling Peaks"] },
    { name: "Activate Lake Tower", types: ["Tower","Lake"] },
    { name: "Any 'Forest Dweller's' Equipment item", types: ["Equipment","Forest Dweller"] },
    { name: "10 Koroks", types: ["Korok"] },
    { name: "Read Zelda's Diary", types: ["Hyrule Castle","Read"] },
    { name: "Pick up Diamond from Satori Mountain", types: ["Rupee","Gems","Ridgeland"] },
    { name: "Killed by a Goat", types: ["Game Over"] },
    { name: "Mauled to Death by a Bear", types: ["Game Over"] },
    { name: "'The Two Rings' Shrine Quest", types: ["Kass","Shrine","Shrine Quest","Ridgeland"] },
    { name: "Any Guardian Sword", types: ["Equipment","Guardian"] },
    { name: "6 Central Tower Koroks", types: ["Korok","Central Hyrule"] },
    { name: "Chilly Elixir", types: ["Cooking","Heat Resistance"] },
    { name: "Mount a Stalhorse", types: ["Mount"] },
    { name: "De-leg a Guardian Stalker But Don't Kill It", types: ["Basic Combat","Guardian"] },
    { name: "Get a Free Elixir from Dueling Peaks Stable NPC", types: ["Dueling Peaks","Misc"] },
    { name: "Die by Heat in the Desert", types: ["Game Over","Wasteland"] },
    { name: "6 Lake Tower Koroks", types: ["Korok","Lake"] },
    { name: "6 Dueling Peaks Koroks", types: ["Korok","Dueling Peaks"] },
    { name: "Any 'Lynel' Equipment item", types: ["Equipment","Lynel"] },
    { name: "Any Electric-typed Equipment item", types: ["Equipment"] },
    { name: "Enduring Elixir", types: ["Cooking","Stamina"] },
    { name: "Fireproof Elixir", types: ["Cooking","Fireproof"] },
    { name: "'Hunt for the Giant Horse' Side Quest", types: ["Side Quest","Lake","Mount","Stamina"] },
    { name: "Activate Ridgeland Tower", types: ["Tower","Ridgeland"] },
    { name: "Any 'Royal Guard's' Equipment item", types: ["Equipment"] },
    { name: "Hard-Boiled Egg", types: ["Cooking","Hyrule Castle"] },
    { name: "Kill a Guardian Scout IV", types: ["Shrine","Guardian"] }
];
bingoList[5] = [
    { name: "Read King's Diary", types: ["Hyrule Castle","Read"] },
    { name: "3 Wasteland Koroks", types: ["Korok","Wasteland"] },
    { name: "'Test of Will' Shrine Quest", types: ["Shrine","Shrine Quest","Gerudo"] },
    { name: "'The Eye of the Sandstorm' Shrine Quest", types: ["Shrine","Shrine Quest","Wasteland"] },
    { name: "Any Hearty Meal", types: ["Cooking"] },
    { name: "Any Enduring Meal", types: ["Cooking","Stamina"] },
    { name: "Any Fairy Tonic", types: ["Cooking"] },
    { name: "Kill a Lynel", types: ["Miniboss","Lynel"] },
    { name: "Kill Colosseum Lynel", types: ["Miniboss","Lynel","Colosseum"] },
    { name: "Kill a Lynel without Ancient Arrows", types:["Miniboss","Lynel"] },
    { name: "Kill a Stone Talus (Rare)", types: ["Miniboss","Talus","Rupee","Gems"] },
    { name: "Any Guardian Shield", types: ["Equipment","Guardian"] },
    { name: "3 Ridgeland Koroks", types: ["Korok","Ridgeland"] },
    { name: "'Riverbed Reward' Side Quest", types: ["Side Quest","Central Hyrule"] },
    { name: "Activate Wasteland Tower", types: ["Tower","Wasteland"] },
    { name: "Collect 50 Apples", types: ["Collector","Misc"] },
    { name: "Kill a (red) Hinox", types: ["Miniboss","Hinox"] },
    { name: "'The Desert Labyrinth' Shrine Quest", types: ["Shrine","Shrine Quest","Wasteland","Barbarian Gear"] },
    { name: "Activate Faron Tower", types: ["Tower","Faron"] },
    { name: "9 Dueling Peaks Koroks", types: ["Korok","Dueling Peaks"] },
    { name: "Obtain 20 Bomb Arrows", types: ["Equipment"] },
    { name: "9 Central Tower Koroks", types: ["Korok","Central Hyrule"] },
    { name: "Kill an electric-typed Wizzrobe", types: ["Basic Combat","Wizzrobe"] },
    { name: "Read Kass's Log Book", types: ["Kass","Ridgeland","Read"] },
    { name: "Kill a Black Hinox", types: ["Miniboss","Hinox"] },
    { name: "Obtain 20 Ice Arrows", types: ["Equipment"] },
    { name: "'An Ice Guy' Side Quest", types: ["Side Quest","Wasteland"] }
];
bingoList[6] = [
    { name: "Kill All Enemies in the Colosseum", types: ["Basic Combat","Miniboss","Lynel","Colosseum"] },
    { name: "Any Chilly Meal", types: ["Cooking","Heat Resistance"] },
    { name: "'The Horseback Hoodlums' Side Quest", types: ["Side Quest","Lake","Basic Combat"] },
    { name: "Block Puzzle Korok Southwest of the 7 Heroines (W40)", types: ["Korok","Wasteland"] },
    { name: "3 Dueling Peaks Shrines", types: ["Shrine","Dueling Peaks"] },
    { name: "3 Faron Koroks", types: ["Korok","Faron"] },
    { name: "Kill an Ice-Typed Wizzrobe", types: ["Basic Combat","Wizzrobe","Heat Resistance"] },
    { name: "Kill a Guardian Skywatcher", types: ["Miniboss","Guardian"] },
    { name: "Mount a Bear", types: ["Mount"] },
    { name: "6 Wasteland Koroks", types: ["Korok","Wasteland"] },
    { name: "Kill a Guardian Turret", types: ["Miniboss","Guardian","Hyrule Castle"] },
    { name: "Open 5 Chests in Shrines", types: ["Shrine"] },
    { name: "Register the Giant Horse", types: ["Mount","Lake","Stamina"] },
    { name: "'Sign of the Shadow' Shrine Quest", types: ["Shrine","Shrine Quest","Gerudo"] },
    { name: "Boat Oar", types: ["Equipment"] },
    { name: "Forgotten Temple Shrine", types: ["Shrine","Shrine Quest","Woodland"] },
    { name: "1 Shrine from 3 Regions", types: ["Shrine"] },
    { name: "'Thunder Magnet' Side Quest", types: ["Side Quest","Faron","Rubber Gear"] },
    { name: "Climber's Bandanna", types: ["Clothes","Climbing Gear"] },
    { name: "9 Lake Tower Koroks", types: ["Korok","Lake"] },
    { name: "Copious Fish Skewers", types: ["Cooking"] },
    { name: "3 Lanayru Koroks", types: ["Korok","Lanayru"] },
    { name: "Salt-Grilled Crab", types: ["Cooking"] },
    { name: "Any Ice-Typed Equipment item", types: ["Equipment","Heat Resistance"] },
    { name: "Any 2nd Tier Rod Weapon", types: ["Equipment","Wizzrobe"] },
    { name: "Mount 3 Different Creatures", types: ["Mount","Stamina"] },
    { name: "6 Ridgeland Koroks", types: ["Korok","Ridgeland"] }
];
bingoList[7] = [
    { name: "Game Over from Lava", types: ["Game Over","Elden"] },
    { name: "Mogg Latan without Windbombs/BLSS", types: ["Ridgeland","Shrine"] },
    { name: "'Playtime with Cottla' Side Quest", types: ["Side Quest","Dueling Peaks"] },
    { name: "'Song of Storms' Shrine Quest", types: ["Shrine","Shrine Quest","Faron"] },
    { name: "Activate Gerudo Tower", types: ["Tower","Gerudo","Cold Resistance"] },
    { name: "12 Central Tower Koroks", types: ["Korok","Central Hyrule"] },
    { name: "Shoot the Targets Korok in Hateno (N45)", types: ["Korok"] },
    { name: "3 Tabantha Koroks", types: ["Korok","Tabantha"] },
    { name: "'The Royal White Stallion' Side Quest", types: ["Side Quest","Central Hyrule","Mount","Stamina"] },
    { name: "Activate Hebra Tower", types: ["Tower","Hebra","Cold Resistance"] },
    { name: "500m in the Gliding Minigame", types: ["Minigame","Ridgeland"] },
    { name: "Obtain 10 Ancient Arrows", types: ["Equipment"] },
    { name: "5 Cube Puzzle Koroks", types: ["Korok"] },
    { name: "Any Apparatus Shrine", types: ["Shrine"] },
    { name: "Attempt to Pull the Master Sword", types: ["Woodland","Master Sword","Korok Forest"] },
    { name: "Kill an Enemy with Master Sword Beams", types: ["Woodland","Master Sword","Korok Forest"] },
    { name: "5 Deer in Hunting Minigame", types: ["Minigame","Hateno"] },
    { name: "3 Gerudo Koroks", types: ["Korok","Gerudo","Cold Resistance"] },
    { name: "3 Woodland Koroks", types: ["Korok","Woodland"] },
    { name: "'The Royal Guard's Gear' Side Quest", types: ["Side Quest","Hyrule Castle"] },
    { name: "12 Dueling Peaks Koroks", types: ["Korok","Dueling Peaks"] },
    { name: "Extravagant Saddle", types: ["Minigame","Mount"] },
    { name: "Rubber Helm", types: ["Clothes","Rubber Gear","Faron"] },
    { name: "Activate Tabantha Tower", types: ["Tower","Tabantha"] },
    { name: "Full Hylian Set", types: ["Clothes","Hylian Gear","Rupee"] },
    { name: "Hylian Hood", types: ["Clothes","Hylian Gear","Rupee"] },
    { name: "Hylian Tunic", types: ["Clothes","Hylian Gear","Rupee"] },
    { name: "Kill a Stalnox", types: ["Miniboss","Hinox"] }
];
bingoList[8] = [
    { name: "Salmon Meuniere", types: ["Cooking"] },
    { name: "'A Gift of Nightshade' Side Quest", types: ["Side Quest","Faron"] },
    { name: "'Crowned Beast' Shrine Quest", types: ["Shrine","Shrine Quest","Hateno","Mount"] },
    { name: "Korok at Top of Highest Castle Spire", types: ["Korok","Hyrule Castle"] },
    { name: "'Secret of the Snowy Peaks' Shrine Quest", types: ["Shrine","Shrine Quest","Wasteland","Cold Resistance"] },
    { name: "Bowl a Strike in the Bowling Minigame", types: ["Minigame","Hebra","Cold Resistance"] },
    { name: "Hylian Shield", types: ["Miniboss","Hinox","Hyrule Castle"] },
    { name: "3 Lake Shrines", types: ["Shrine","Lake"] },
    { name: "Pay 1 Great Fairy", types: ["Rupee","Great Fairy"] },
    { name: "'A Freezing Rod' Side Quest", types: ["Side Quest","Woodland","Wizzrobe","Heat Resistance"] },
    { name: "Activate Woodland Tower", types: ["Tower","Woodland"] },
    { name: "12 Lake Tower Koroks", types: ["Korok","Lake"] },
    { name: "Attempt to Register an Un-Registrable Mount at a Stable", types: ["Mount"] },
    { name: "Open all Chests in Mirro Shaz Shrine", types: ["Shrine"] },
    { name: "'A Landscape of a Stable' Shrine Quest", types: ["Shrine","Shrine Quest","Eldin"] },
    { name: "15 Central Tower Koroks", types: ["Korok","Central Hyrule"] },
    { name: "3 Hateno Koroks", types: ["Korok","Hateno"] },
    { name: "1 Korok Trial", types: ["Shrine","Shrine Quest","Woodland","Korok Forest"] },
    { name: "50 Elemental Arrows", types: ["Equipment"] },
    { name: "1 Fire, 1 Ice, and 1 Electric Weapons", types: ["Equipment","Heat Resistance","Cold Resistance"] },
    { name: "Activate Lanayru Tower", types: ["Tower","Lanayru"] },
    { name: "Buy from Beedle in 3 Locations", types: ["Beedle"] },
    { name: "Wheat Bread", types: ["Cooking"] },
    { name: "Register a 5-Spur Horse (not Epona, Giant, or Royal)", types: ["Mount","Stamina"] },
    { name: "'Balloon Flight' Side Quest", types: ["Side Quest","Woodland"] },
    { name: "Activate Eldin Tower", types: ["Tower","Eldin"] },
    { name: "Read Paya's Diary", types: ["Dueling Peaks","Read"] },
    { name: "Rubber Tights", types: ["Clothes","Rubber Gear","Faron"] },
    { name: "Activate Hateno Tower", types: ["Tower","Hateno"] },
    { name: "Obtain a Kite Shield", types: ["Equipment","Hateno","Cold Resistance"] },
    { name: "Obtain Great Flameblade from Eldin Leviathan", types: ["Equipment","Eldin","Cold Resistance"] }
];
bingoList[9] = [
    { name: "Activate Wasteland and Gerudo Towers", types: ["Tower","Wasteland","Gerudo"] },
    { name: "Finish Golf Minigame", types: ["Minigame","Ridgeland"] },
    { name: "6 Lanayru Koroks", types: ["Korok. Lanayru"] },
    { name: "Obtain 5 fairies", types: ["Fairy","Great Fairy"] },
    { name: "9 Ridgeland Koroks", types: ["Korok","Ridgeland"] },
    { name: "9 Wasteland Koroks", types: ["Korok","Wasteland"] },
    { name: "3 Central Tower Shrines", types: ["Shrine","Central Hyrule"] },
    { name: "Obtain 7 fairies", types: ["Fairy","Great Fairy"] },
    { name: "Open 5 Chests in a Labyrinth", types: ["Shrine"] },
    { name: "1 Shrine from 4 Regions", types: ["Shrine"] },
    { name: "Defeat 3 Lynels", types: ["Miniboss", "Lynel"] },
    { name: "Complete the korok on top of the gambler's hut (F36)", types: ["Korok", "Faron"] },
    { name: "Forest Dweller's Bow, Shield, Sword, and Spear", types: ["Equipment","Forest Dweller","Korok Forest"] },
    { name: "'A Gift for the Great Fairy' Side Quest", types: ["Side Quest","Tabantha","Rupee","Great Fairy"] },
    { name: "'Sunken Treasure' Side Quest", types: ["Side Quest","Faron"] },
    { name: "'The Apple of My Eye' Side Quest", types: ["Side Quest","Tabantha"] },
    { name: "'Wild Horses' Side Quest", types: ["Side Quest","Dueling Peaks","Mount"] },
    { name: "Any Guardian Battle Axe", types: ["Equipment","Guardian"] },
    { name: "Extravagant Bridle", types: ["Minigame","Mount"] },
    { name: "6 Faron Koroks", types: ["Korok","Faron"] },
    { name: "5 Goal Ring Koroks", types: ["Korok"] },
    { name: "Rubber Armor", types: ["Clothes","Rubber Gear","Ridgeland"] },
    { name: "6 Tabantha Koroks", types: ["Korok","Tabantha"] },
    { name: "'The Hero's Cache' Side Quest", types: ["Side Quest","Hateno","Rupee"] },
    { name: "Cream of Mushroom Soup", types: ["Cooking"] },
    { name: "'Arrows of Burning Heat' Side Quest", types: ["Side Quest","Dueling Peaks"] },
    { name: "'The Priceless Maracas' Side Quest", types: ["Side Quest","Dueling Peaks"] }
];
bingoList[10] = [
    { name: "Bowl a Spare in the Bowling Minigame", types: ["Minigame","Hebra","Cold Resistance"] },
    { name: "2 Dog Treasures", types: ["Dog Treasure"] },
    { name: "Hylian Trousers ★", types: ["Clothes","Hylian Gear","Rupee","Great Fairy"] },
    { name: "Sleep in 3 Different Beds", types: ["Bed"] },
    { name: "Snowquill Trousers", types: ["Clothes","Snow Gear","Cold Resistance","Rupee","Tabantha"] },
    { name: "Snowquill Tunic", types: ["Clothes","Snow Gear","Cold Resistance","Rupee","Tabantha"] },
    { name: "Stealth Chest Guard", types: ["Clothes","Stealth Gear","Rupee","Dueling Peaks"] },
    { name: "Stealth Mask", types: ["Clothes","Stealth Gear","Rupee","Dueling Peaks"] },
    { name: "Stealth Tights", types: ["Clothes","Stealth Gear","Rupee","Dueling Peaks"] },
    { name: "'Missing in Action' Side Quest", types: ["Side Quest","Wasteland"] },
    { name: "15 Dueling Peaks Koroks", types: ["Korok","Dueling Peaks"] },
    { name: "3 Eldin Koroks", types: ["Korok","Eldin","Fireproof"] },
    { name: "Fruitcake", types: ["Cooking"] },
    { name: "15 Lake Tower Koroks", types: ["Korok","Lake"] },
    { name: "3 Ridgeland Shrines", types: ["Shrine","Ridgeland"] },
    { name: "'Master of the Wind' Shrine Quest", types: ["Shrine","Shrine Quest","Lanayru"] },
    { name: "A Modest Test of Strength Shrine", types: ["Shrine","Guardian"] },
    { name: "Kill an Igneo Talus", types: ["Miniboss","Talus","Rupee","Gems","Eldin","Fireproof"] },
    { name: "Obtain a Material directly from Farosh", types: ["Dragon"] },
    { name: "'The Cursed Statue' Shrine Quest", types: ["Shrine","Shrine Quest","Hateno"] },
    { name: "Flamebreaker Armor", types: ["Clothes","Flame Gear","Eldin","Rupee","Fireproof"] },
    { name: "Kill a Frost Talus", types: ["Miniboss","Talus","Rupee","Gems","Cold Resistance"] },
    { name: "Refine a Rusty Shield using an Octorok", types: ["Equipment"] },
    { name: "12 Ridgeland Koroks", types: ["Korok","Ridgeland"] },
    { name: "2 Shrine Quests", types: ["Shrine","Shrine Quest"] }
];
bingoList[11] = [
    { name: "Unlock a Horned Chest in a Hebra Enemy Camp", types: ["Basic Combat","Hebra","Cold Resistance"] },
    { name: "3 Side Quests", types: ["Side Quest"] },
    { name: "6 Woodland Koroks", types: ["Korok","Woodland"] },
    { name: "5 Heart Containers", types: ["Shrine"] },
    { name: "Monster cake", types: ["Cooking"] },
    { name: "Obtain 20 Shock Arrows", types: ["Equipment"] },
    { name: "Read Robbie's Diary", types: ["Akkala","Read"] },
    { name: "2000 Rupees", types: ["Rupee"] },
    { name: "Snowquill Headdress", types: ["Clothes","Snow Gear","Cold Resistance","Rupee","Tabantha"] },
    { name: "2 Stamina Vessels", types: ["Shrine","Stamina"] },
    { name: "'Twin Memories' Shrines", types: ["Shrine","Shrine Quest","Dueling Peaks"] },
    { name: "'Shrouded Shrine' Shrine Quest", types: ["Shrine","Shrine Quest","Woodland"] },
    { name: "Apple Pie", types: ["Cooking","Tabantha"] },
    { name: "Barbarian Armor", types: ["Clothes","Barbarian Gear","Wasteland"] },
    { name: "Finish Basic Shield Surfing Minigame", types: ["Minigame","Hebra","Cold Resistance"] },
    { name: "Full Stealth Set", types: ["Clothes","Stealth Gear","Rupee","Dueling Peaks"] },
    { name: "Hylian Hood ★", types: ["Clothes","Hylian Gear","Rupee","Great Fairy"] },
    { name: "Hylian Tunic ★", types: ["Clothes","Hylian Gear","Rupee","Great Fairy"] },
    { name: "Kill a Molduga", types: ["Miniboss","Molduga","Wasteland"] },
    { name: "4 Side Quests", types: ["Side Quest"] },
    { name: "4 Koko Cooking Side Quests", types: ["Side Quest","Dueling Peaks"] },
    { name: "3 Lanayru Shrines", types: ["Shrine","Lanayru"] },
    { name: "6 Eldin Koroks", types: ["Korok","Eldin","Fireproof"] },
    { name: "6 Hateno Koroks", types: ["Korok","Hateno"] },
    { name: "3 Hebra Koroks", types: ["Korok","Hebra","Cold Resistance"] },
    { name: "9 Lanayru Koroks", types: ["Korok. Lanayru"] }
];
bingoList[12] = [
    { name: "Pay Horse God Malanya", types: ["Lake","Rupee","Malanya"] },
    { name: "Sail to Eventide Island Using a Raft and Korok Leaf", types: ["Faron","Eventide"] },
    { name: "5 Pinwheel Balloon Koroks", types: ["Korok"] },
    { name: "Zora Armor", types: ["Clothes","Zora Gear","Lanayru"] },
    { name: "Activate Akkala Tower", types: ["Tower","Akkala"] },
    { name: "3 Faron Shrines", types: ["Shrine","Faron"] },
    { name: "12 Wasteland Koroks", types: ["Korok","Wasteland"] },
    { name: "Complete the Goal Ring Korok in Northern Hebra (H07)", types: ["Korok","Hebra","Cold Resistance"] },
    { name: "Obtain 3 Types of Great Elemental Blades", types: ["Equipment","Heat Resistance","Cold Resistance"] },
    { name: "'Misko, the Great Bandit' Side Quest", types: ["Side Quest","Dueling Peaks","Cold Resistance","Gems"] },
    { name: "3 Akkala Koroks", types: ["Korok","Akkala"] },
    { name: "'Cliffside Etchings' Shrine Quest", types: ["Shrine","Shrine Quest","Gerudo","Cold Resistance"] },
    { name: "'Flown the Coop' Side Quest", types: ["Side Quest","Dueling Peaks","Heirloom"] },
    { name: "'My Hero' Side Quest", types: ["Side Quest","Master Sword"] },
    { name: "15 Koroks", types: ["Korok"] },
    { name: "Talk to Kilton", types: ["Kilton","Akkala"] },
    { name: "'A Gift for My Beloved' Side Quest", types: ["Side Quest","Hateno"] },
    { name: "'The Spark of Romance' Side Quest", types: ["Side Quest","Tabantha"] },
    { name: "'The Statue's Bargain' Side Quest", types: ["Side Quest","Hateno"] },
    { name: "Gerudo Set", types: ["Clothes","Rupee","Gerudo Set","Heat Resistance"] },
    { name: "5 Unique Royal Guard Weapons", types: ["Equipment"] },
    { name: "Activate Central and Akkala Towers", types: ["Tower","Central Hyrule","Akkala"] },
    { name: "Complete 2 Kass Quests", types: ["Shrine Quest", "Side Quest","Kass"] },
    { name: "9 Tabantha Koroks", types: ["Korok","Tabantha"] },
    { name: "3 Wasteland Shrines", types: ["Shrine","Wasteland"] },
    { name: "Obtain Great Flameblade from Lomei Labyrinth", types: ["Equipment","Akkala","Cold Resistance"] },
    { name: "Zora Helm", types: ["Clothes","Zora Gear","Lanayru"] },
    { name: "Soldier's Armor", types: ["Clothes","Soldier Gear","Rupee","Hateno"] },
    { name: "Soldier's Greaves", types: ["Clothes","Soldier Gear","Rupee","Hateno"] },
    { name: "Soldier's Helm", types: ["Clothes","Soldier Gear","Rupee","Hateno"] }
];
bingoList[13] = [
    { name: "Stealth Chest Guard ★", types: ["Clothes","Stealth Gear","Rupee","Great Fairy"] },
    { name: "Stealth Mask ★", types: ["Clothes","Stealth Gear","Rupee","Great Fairy"] },
    { name: "Stealth Tights ★", types: ["Clothes","Stealth Gear","Rupee","Great Fairy"] },
    { name: "6 Gerudo Koroks", types: ["Korok","Gerudo","Cold Resistance"] },
    { name: "Mount the Lord of the Mountain", types: ["Mount","Ridgeland","Stamina"] },
    { name: "'Fireproof Lizard Roundup' Side Quest", types: ["Side Quest","Eldin","Flame Gear","Fireproof"] },
    { name: "Climber's Bandanna ★", types: ["Clothes","Climbing Gear","Great Fairy"] },
    { name: "15 Ridgeland Koroks", types: ["Korok","Ridgeland"] },
    { name: "3 Dog Treasures", types: ["Dog Treasure"] },
    { name: "'Diving is Beauty!' Side Quest", types: ["Side Quest","Lanayru"] },
    { name: "'Three Giant Brothers' Shrine Quest", types: ["Shrine","Shrine Quest","Faron","Miniboss","Hinox"] },
    { name: "Snowquill Trousers ★", types: ["Clothes","Snow Gear","Cold Resistance","Rupee","Great Fairy"] },
    { name: "Snowquill Tunic ★", types: ["Clothes","Snow Gear","Cold Resistance","Rupee","Great Fairy"] },
    { name: "3 Eldin Shrines", types: ["Shrine","Eldin","Fireproof"] },
    { name: "3 Tabantha Shrines", types: ["Shrine","Tabantha"] },
    { name: "'The Secret Club's Secret' Side Quest", types: ["Side Quest","Gerudo Set","Wasteland"] },
    { name: "Creamy Heart Soup", types: ["Cooking"] },
    { name: "12 Lanayru Koroks", types: ["Korok. Lanayru"] },
    { name: "Mount 5 Different Creatures", types: ["Mount","Stamina"] },
    { name: "'A Royal Recipe' Side Quest", types: ["Side Quest","Central Hyrule","Cooking"] },
    { name: "'Secret of the Cedars' Shrine Quest", types: ["Shrine","Shrine Quest","Hateno"] },
    { name: "Buy from Beedle in 5 Locations", types: ["Beedle"] },
    { name: "Climbing Gear", types: ["Clothes","Climbing Gear","Hateno"] },
    { name: "Desert Voe Headband", types: ["Clothes","Desert Gear","Rupee","Gerudo Set","Heat Resistance"] },
    { name: "Desert Voe Trousers", types: ["Clothes","Desert Gear","Rupee","Gerudo Set","Heat Resistance"] }
];
bingoList[14] = [
    { name: "'Take Back the Sea' Side Quest", types: ["Side Quest","Faron","Basic Combat"] },
    { name: "Akkala 'Trial of the Labyrinth' Shrine Quest", types: ["Shrine","Shrine Quest","Akkala","Barbarian Gear"] },
    { name: "6 Akkala Koroks", types: ["Korok","Akkala"] },
    { name: "9 Eldin Koroks", types: ["Korok","Eldin","Fireproof"] },
    { name: "9 Faron Koroks", types: ["Korok","Faron"] },
    { name: "Obtain a Material directly from Dinraal", types: ["Dragon"] },
    { name: "Full Soldier's Set", types: ["Clothes","Soldier Gear","Rupee","Hateno"] },
    { name: "Black Dyed Hylian Hood", types: ["Clothes","Hylian Gear","Hateno"] },
    { name: "Blue Dyed Hylian Hood", types: ["Clothes","Hylian Gear","Hateno"] },
    { name: "Brown Dyed Hylian Hood", types: ["Clothes","Hylian Gear","Hateno"] },
    { name: "Crimson Dyed Hylian Hood", types: ["Clothes","Hylian Gear","Hateno"] },
    { name: "Gray Dyed Hylian Hood", types: ["Clothes","Hylian Gear","Hateno"] },
    { name: "Green Dyed Hylian Hood", types: ["Clothes","Hylian Gear","Hateno"] },
    { name: "Light Blue Dyed Hylian Hood", types: ["Clothes","Hylian Gear","Hateno"] },
    { name: "Light Yellow Dyed Hylian Hood", types: ["Clothes","Hylian Gear","Hateno"] },
    { name: "Navy Dyed Hylian Hood", types: ["Clothes","Hylian Gear","Hateno"] },
    { name: "Orange Dyed Hylian Hood", types: ["Clothes","Hylian Gear","Hateno"] },
    { name: "Peach Dyed Hylian Hood", types: ["Clothes","Hylian Gear","Hateno"] },
    { name: "Purple Dyed Hylian Hood", types: ["Clothes","Hylian Gear","Hateno"] },
    { name: "Red Dyed Hylian Hood", types: ["Clothes","Hylian Gear","Hateno"] },
    { name: "White Dyed Hylian Hood", types: ["Clothes","Hylian Gear","Hateno"] },
    { name: "Yellow Dyed Hylian Hood", types: ["Clothes","Hylian Gear","Hateno"] },
    { name: "Discover 1 Secret Hot Spring", types: ["Hebra", "Cold Resistance"] },
    { name: "9 Hateno Koroks", types: ["Korok","Hateno","Cold Resistance"] },
    { name: "Read Purah's Diary", types: ["Hateno","Read"] },
    { name: "Knight's Bridle", types: ["Minigame","Mount"] },
    { name: "Get Some Advice from Patricia the Sand Seal", types: ["Gerudo Set"] },
    { name: "Give Beedle one of Each Kind of Beetle", types: ["Beedle"] },
    { name: "Rubber Armor ★", types: ["Clothes","Rubber Gear","Ridgeland","Great Fairy"] },
    { name: "Rubber Helm ★", types: ["Clothes","Rubber Gear","Faron","Great Fairy"] },
    { name: "Sleep in 5 Different Beds", types: ["Bed"] }
];
bingoList[15] = [
    { name: "Make an Outfit of 3 Different Colors Using Dye", types: ["Clothes","Hateno"] },
    { name: "15 Wasteland Koroks", types: ["Korok","Wasteland"] },
    { name: "9 Woodland Koroks", types: ["Korok","Woodland"] },
    { name: "Barbarian Helm", types: ["Clothes","Barbarian Gear","Akkala"] },
    { name: "Honey Crepe", types: ["Cooking"] },
    { name: "Wildberry Crepe", types: ["Cooking","Tabantha"] },
    { name: "Complete Kah Mael Shrine (Tingel island)", types: ["Shrine","Lanayru"] },
    { name: "A Major Test of Strength Shrine", types: ["Shrine","Guardian"] },
    { name: "Crab Risotto", types: ["Cooking"] },
    { name: "Desert Voe Spaulder", types: ["Clothes","Desert Gear","Rupee","Gerudo Set"] },
    { name: "Flamebreaker Boots", types: ["Clothes","Flame Gear","Eldin","Rupee","Fireproof"] },
    { name: "6 Hebra Koroks", types: ["Korok","Hebra","Cold Resistance"] },
    { name: "10 Shrines", types: ["Shrine"] },
    { name: "Snowquill Headdress ★", types: ["Clothes","Snow Gear","Cold Resistance","Rupee","Great Fairy"] },
    { name: "'The Silent Swordswomen' Shrine Quest", types: ["Shrine","Shrine Quest","Wasteland"] },
    { name: "Open 10 Chests in Labyrinths", types: ["Shrine"] },
    { name: "Take a Selfie with Kass", types: ["Camera","Kass"] },
    { name: "Eat Rock-Hard Food Made from 5 Diamonds", types: ["Cooking","Gems"] },
    { name: "Hebra Labyrinth 'Trial on the Cliff' Shrine Quest", types: ["Shrine","Shrine Quest","Hebra","Cold Resistance","Barbarian Gear"] },
    { name: "Take a Selfie while on fire", types: ["Camera"] },
    { name: "'Into the Vortex' Shrine Quest", types: ["Shrine","Shrine Quest","Akkala"] },
    { name: "Diamond Circlet", types: ["Clothes","Gems","Rupee","Gerudo Set","Akkala"] },
    { name: "10 Castle Koroks", types: ["Korok","Hyrule Castle"] },
    { name: "'The Serpent's Jaws' Shrine Quest", types: ["Shrine","Shrine Quest","Lake","Dragon"] },
    { name: "Barbarian Leg Wraps", types: ["Clothes","Barbarian Gear","Hebra"] },
    { name: "'Death Mountain's Secret' Side Quest", types: ["Side Quest","Eldin","Fireproof"] },
    { name: "15 Lanayru Koroks", types: ["Korok. Lanayru"] },
    { name: "Take a Selfie with Hestu", types: ["Dueling Peaks","Camera"] },
    { name: "Sheikah Sensor +", types: ["Camera","Rune Upgrade","Hateno"] }
];
bingoList[16] = [
    { name: "Zora Helm ★", types: ["Clothes","Zora Gear","Great Fairy","Lizalfos"] },
    { name: "Activate Woodland and Hateno Towers", types: ["Tower","Woodland","Hateno"] },
    { name: "12 Tabantha Koroks", types: ["Korok","Tabantha"] },
    { name: "Kill the Hinox in the Thyphlo Ruins", types: ["Miniboss","Hinox","Woodland"] },
    { name: "Tho Kayu (Molduga Shrine)", types: ["Shrine","Miniboss","Molduga","Wasteland"] },
    { name: "'The Sheep Rustlers' Side Quest", types: ["Side Quest","Hateno","Basic Combat"] },
    { name: "Climbing Boots", types: ["Clothes","Climbing Gear","Hateno"] },
    { name: "Complete 3 Kass Quests", types: ["Shrine Quest", "Side Quest","Kass"] },
    { name: "Knight's Saddle", types: ["Minigame","Mount"] },
    { name: "20 Koroks", types: ["Korok"] },
    { name: "Feed a Fish, a Dog, a Sheep, and a Cow", types: ["Dog Treasure","Hateno"] },
    { name: "12 Woodland Koroks", types: ["Korok","Woodland"] },
    { name: "9 Gerudo Koroks", types: ["Korok","Gerudo","Cold Resistance"] },
    { name: "Take a Selfie with a Lynel", types: ["Camera","Compendium","Lynel"] },
    { name: "'The Bird in the Mountains' Shrine Quest", types: ["Shrine","Shrine Quest","Hebra","Cold Resistance"] },
    { name: "'What's for Dinner?' Side Quest", types: ["Side Quest","Faron"] },
    { name: "9 Akkala Koroks", types: ["Korok","Akkala"] },
    { name: "12 Faron Koroks", types: ["Korok","Faron"] },
    { name: "Seafood Paella", types: ["Cooking"] },
    { name: "3 Woodland Shrines", types: ["Shrine","Woodland"] },
    { name: "'The Seven Heroines' Shrine Quest", types: ["Shrine","Shrine Quest","Gerudo Set"] },
    { name: "Discover 2 Secret Hot Springs", types: ["Hebra", "Cold Resistance"] },
    { name: "Full Snowquill Set", types: ["Clothes","Snow Gear","Cold Resistance","Rupee","Tabantha"] },
    { name: "12 Eldin Koroks", types: ["Korok","Eldin","Fireproof"] },
    { name: "Full Rubber Set", types: ["Clothes","Rubber Gear","Faron","Ridgeland"] },
    { name: "Rubber Tights ★", types: ["Clothes","Rubber Gear","Faron","Great Fairy"] },
    { name: "Zora Armor ★", types: ["Clothes","Zora Gear","Great Fairy","Lizalfos"] },
    { name: "'The Spring of Power' Shrine Quest", types: ["Shrine","Shrine Quest","Akkala","Dragon"] }
];
bingoList[17] = [
    { name: "Activate Hebra and Eldin Towers", types: ["Tower","Hebra","Elden"] },
    { name: "Free Naydra", types: ["Dragon"] },
    { name: "12 Hateno Koroks", types: ["Korok","Hateno"] },
    { name: "1 Shrine from 5 Regions", types: ["Shrine"] },
    { name: "Soldier's Armor ★", types: ["Clothes","Soldier Gear","Rupee","Great Fairy"] },
    { name: "Soldier's Greaves ★", types: ["Clothes","Soldier Gear","Rupee","Great Fairy"] },
    { name: "Soldier's Helm ★", types: ["Clothes","Soldier Gear","Rupee","Great Fairy"] },
    { name: "Buy from Beedle in 7 Locations", types: ["Beedle"] },
    { name: "Pay 2 Great Fairies", types: ["Rupee","Great Fairy"] },
    { name: "Read 10 books", types: ["Read"] },
    { name: "Activate 4 Towers", types: ["Tower"] },
    { name: "Discover 3 Secret Hot Springs", types: ["Hebra", "Cold Resistance"] },
    { name: "3 Hateno Shrines", types: ["Shrine","Hateno"] },
    { name: "Take a Selfie with Sidon", types: ["Lanayru","Camera"] },
    { name: "Barbarian Armor ★", types: ["Clothes","Barbarian Gear","Great Fairy","Miniboss","Lynel"] },
    { name: "Activate a Tech Lab Using Arrows Only", types: ["Hateno","Akkala","Camera"] },
    { name: "'Find the Fairy Fountain' Main Quest", types: ["Hateno","Camera","Main Quest"] },
    { name: "5 Creatures in Compendium", types: ["Camera","Compendium"] },
    { name: "5 Equipment in Compendium", types: ["Camera","Compendium"] },
    { name: "10 Cube Puzzle Koroks", types: ["Korok"] },
    { name: "Flamebreaker Helm", types: ["Clothes","Flame Gear","Eldin","Rupee","Fireproof"] },
    { name: "4 Dog Treasures", types: ["Dog Treasure"] },
    { name: "11 Shrines", types: ["Shrine"] },
    { name: "3 Apparatus Shrines", types: ["Shrine"] },
    { name: "15 Faron Koroks", types: ["Korok","Faron"] },
    { name: "'Little Sister's Big Request' Side Quest", types: ["Side Quest","Akkala"] },
    { name: "Remote Bomb +", types: ["Camera","Rune Upgrade","Hateno"] },
    { name: "Rescue Yunobo", types: ["Eldin","Fireproof"] },
    { name: "'Luminous Stone Gathering' Side Quest", types: ["Side Quest","Lanayru","Rupee","Gems"] }
];
bingoList[18] = [
    { name: "9 Hebra Koroks", types: ["Korok","Hebra","Cold Resistance"] },
    { name: "3 Hebra Shrines", types: ["Shrine","Hebra","Cold Resistance"] },
    { name: "Climbing Boots ★", types: ["Clothes","Climbing Gear","Great Fairy"] },
    { name: "Collect 1 Picture Memory", types: ["Camera"] },
    { name: "Desert Voe Headband ★", types: ["Clothes","Desert Gear","Rupee","Great Fairy","Gerudo Set","Heat Resistance"] },
    { name: "Desert Voe Trousers ★", types: ["Clothes","Desert Gear","Rupee","Great Fairy","Gerudo Set","Heat Resistance"] },
    { name: "Desert Voe Spaulder ★", types: ["Clothes","Desert Gear","Rupee","Great Fairy","Gerudo Set","Heat Resistance"] },
    { name: "Obtain 4 Rubies, 4 Diamonds, and 4 Sapphires", types: ["Gems","Rupee"] },
    { name: "12 Gerudo Koroks", types: ["Korok","Gerudo"] },
    { name: "12 Akkala Koroks", types: ["Korok","Akkala"] },
    { name: "5 Monsters in Compendium", types: ["Camera","Compendium"] },
    { name: "15 Woodland Koroks", types: ["Korok","Woodland"] },
    { name: "'Sunshroom Sensing' Side Quest", types: ["Side Quest","Hateno","Camera"] },
    { name: "3 Bird Pictures in Compendium", types: ["Camera", "Compendium"] },
    { name: "1 Shrine from 6 Regions", types: ["Shrine"] },
    { name: "3 Akkala Shrines", types: ["Shrine","Akkala"] },
    { name: "Barbarian Leg Wraps ★", types: ["Clothes","Barbarian Gear","Great Fairy","Miniboss","Lynel"] },
    { name: "'The Spring of Wisdom' Shrine Quest", types: ["Shrine","Shrine Quest","Hateno","Cold Resistance","Dragon"] },
    { name: "10 Equipment in Compendium", types: ["Camera","Compendium"] },
    { name: "10 Creatures in Compendium", types: ["Camera","Compendium"] },
    { name: "Flamebreaker Armor ★", types: ["Clothes","Flame Gear","Eldin","Rupee","Great Fairy","Fireproof"] },
    { name: "2 Labyrinth Shrine Quests", types: ["Shrine","Shrine Quest"] },
    { name: "15 Tabantha Koroks", types: ["Korok","Tabantha"] },
    { name: "12 Shrines", types: ["Shrine"] },
    { name: "Champion's Tunic", types: ["Clothes","Champion","Camera"] }
];
bingoList[19] = [
    { name: "'Fragmented Monument' Shrine Quest", types: ["Shrine","Shrine Quest","Faron","Camera"] },
    { name: "'Medicinal Molduga' Side Quest", types: ["Side Quest","Gerudo Set","Miniboss","Molduga"] },
    { name: "'Stranded on Eventide' Shrine Quest", types: ["Shrine","Shrine Quest","Faron","Eventide"] },
    { name: "Buy a House", types: ["Hateno","Rupee"] },
    { name: "Collect 2 Picture Memories", types: ["Camera"] },
    { name: "Complete 4 Kass Quests", types: ["Shrine Quest", "Side Quest","Kass"] },
    { name: "Bokoblin Mask", types: ["Clothes","Kilton"] },
    { name: "12 Hebra Koroks", types: ["Korok","Hebra","Cold Resistance"] },
    { name: "25 Koroks", types: ["Korok"] },
    { name: "'Brother's Roast' Shrine Quest", types: ["Shrine","Shrine Quest","Eldin","Fireproof"] },
    { name: "'The Road to Respect' Side Quest", types: ["Miniboss","Talus","Rupee","Gems","Side Quest","Eldin","Fireproof"] },
    { name: "15 Eldin Koroks", types: ["Korok","Eldin","Fireproof"] },
    { name: "'The Gut Check Challenge' Shrine Quest", types: ["Shrine","Shrine Quest","Eldin","Fireproof"] },
    { name: "Curry Pilaf", types: ["Cooking","Eldin","Fireproof"] },
    { name: "13 Shrines", types: ["Shrine"] },
    { name: "Flamebreaker Boots ★", types: ["Clothes","Flame Gear","Eldin","Rupee","Great Fairy","Fireproof"] },
    { name: "3 Gerudo Shrines", types: ["Shrine","Gerudo","Fireproof"] },
    { name: "6 Heart Containers", types: ["Shrine","Heart"] },
    { name: "Amber Earrings", types: ["Clothes","Gems","Rupee","Gerudo Set"] },
    { name: "15 Equipment in Compendium", types: ["Camera","Compendium"] },
    { name: "Opal Earrings", types: ["Clothes","Gems","Rupee","Gerudo Set"] },
    { name: "Radiant Mask", types: ["Clothes","Radiant Gear","Rupee","Gems","Gerudo Set"] },
    { name: "Radiant Shirt", types: ["Clothes","Radiant Gear","Rupee","Gems","Gerudo Set"] },
    { name: "Radiant Tights", types: ["Clothes","Radiant Gear","Rupee","Gems","Gerudo Set"] },
    { name: "Ruby Circlet", types: ["Clothes","Gems","Rupee","Gerudo Set"] },
    { name: "Sapphire Circlet", types: ["Clothes","Gems","Rupee","Gerudo Set"] },
    { name: "Topaz Earrings", types: ["Clothes","Gems","Rupee","Gerudo Set"] },
    { name: "'Tools of the Trade' Side Quest", types: ["Side Quest","Gerudo Set","Rupee","Gems"] }
];
bingoList[20] = [
    { name: "Champion's Tunic ★", types: ["Clothes","Champion","Camera","Great Fairy"] },
    { name: "15 Akkala Koroks", types: ["Korok","Akkala"] },
    { name: "Collect 3 Picture Memories", types: ["Camera"] },
    { name: "Full Climber's Set", types: ["Clothes","Climbing Gear"] },
    { name: "Take a Picture of all 4 Guardian Scout Types", types: ["Guardian", "Camera", "Compendium"] },
    { name: "5 Bird Pictures in Compendium", types: ["Camera", "Compendium"] },
    { name: "10 Monsters in Compendium", types: ["Camera","Compendium"] },
    { name: "Stasis +", types: ["Camera","Rune Upgrade","Hateno"] },
    { name: "15 Gerudo Koroks", types: ["Korok","Gerudo","Cold Resistance"] },
    { name: "1 Shrine from 7 Regions", types: ["Shrine"] },
    { name: "3 Stamina Vessels", types: ["Shrine","Stamina"] },
    { name: "Barbarian Helm ★", types: ["Clothes","Barbarian Gear","Great Fairy","Miniboss","Lynel"] },
    { name: "14 Shrines", types: ["Shrine"] },
    { name: "Activate 5 Towers", types: ["Tower"] },
    { name: "10 Pinwheel Balloon Koroks", types: ["Korok"] },
    { name: "Collect 4 Picture Memories", types: ["Camera"] },
    { name: "15 Hateno Koroks", types: ["Korok","Hateno","Cold Resistance"] },
    { name: "'Curry for What Ails You' Side Quest", types: ["Side Quest","Tabantha","Eldin","Fireproof"] },
    { name: "Obtain a Material directly from Naydra", types: ["Hateno","Cold Resistance","Dragon"] },
    { name: "Zora Greaves", types: ["Clothes","Zora Gear","Lanayru","Camera"] },
    { name: "15 Creatures in Compendium", types: ["Camera","Compendium"] },
    { name: "Radiant Mask ★", types: ["Clothes","Radiant Gear","Rupee","Gems","Great Fairy","Gerudo Set"] },
    { name: "Radiant Shirt ★", types: ["Clothes","Radiant Gear","Rupee","Gems","Great Fairy","Gerudo Set"] },
    { name: "Radiant Tights ★", types: ["Clothes","Radiant Gear","Rupee","Gems","Great Fairy","Gerudo Set"] }
];
bingoList[21] = [
    { name: "'Stranded on Eventide' Shrine Quest Without Smuggling", types: ["Shrine","Shrine Quest","Faron","Eventide"] },
    { name: "20 Equipment in Compendium", types: ["Camera","Compendium"] },
    { name: "Mount 7 Different Creatures", types: ["Mount","Stamina"] },
    { name: "'By Firefly's Light' Side Quest", types: ["Side Quest","Dueling Peaks","Heirloom","Camera"] },
    { name: "Climbing Gear ★", types: ["Clothes","Climbing Gear","Great Fairy"] },
    { name: "Amber Earrings ★", types: ["Clothes","Gems","Rupee","Great Fairy"] },
    { name: "Opal Earrings ★", types: ["Clothes","Gems","Rupee","Great Fairy"] },
    { name: "Topaz Earrings ★", types: ["Clothes","Gems","Rupee","Great Fairy"] },
    { name: "Ruby Circlet ★", types: ["Clothes","Gems","Rupee","Great Fairy","Cold Resistance"] },
    { name: "Sapphire Circlet ★", types: ["Clothes","Gems","Rupee","Great Fairy","Heat Resistance"] },
    { name: "Complete the Super Gut Check Challenge", types: ["Shrine", "Stamina"] },
    { name: "Complete 5 Kass Quests", types: ["Shrine Quest", "Side Quest","Kass"] },
    { name: "Do a Side Quest in 4 Different Villages", types: ["Side Quest"] },
    { name: "'Lynel Safari' Side Quest", types: ["Side Quest","Lanayru","Camera","Zora Gear"] },
    { name: "30 Koroks", types: ["Korok"] },
    { name: "Pay 3 Great Fairies", types: ["Rupee","Great Fairy"] },
    { name: "Complete the Yiga Clan Hideout & Kohga Without Skips", types: ["Miniboss"] },
    { name: "Windcleaver", types: ["Equipment","Gerudo Set"] },
    { name: "'Guardian Slideshow' Shrine Quest", types: ["Shrine","Shrine Quest","Lake","Camera","Guardian"] },
    { name: "5 Blessing Shrines", types: ["Shrine","Shrine Quest"] },
    { name: "'A Shady Customer' Side Quest", types: ["Side Quest","Akkala","Kilton","Camera"] },
    { name: "15 Hebra Koroks", types: ["Korok","Hebra","Cold Resistance"] },
    { name: "15 Shrines", types: ["Shrine"] },
    { name: "Activate 6 Towers", types: ["Tower"] },
    { name: "Take a Selfie with Riju", types: ["Gerudo Set","Camera"] },
    { name: "Collect 5 Picture Memories", types: ["Camera"] },
    { name: "'Stalhorse: Pictured!' Side Quest", types: ["Side Quest","Hebra","Camera"] }
];
bingoList[22] = [
    { name: "20 Creatures in Compendium", types: ["Camera","Compendium"] },
    { name: "Full Desert Voe Set", types: ["Clothes","Desert Gear","Rupee","Gerudo Set","Heat Resistance"] },
    { name: "5 Shrine Quests", types: ["Shrine","Shrine Quest"] },
    { name: "Sleep in 10 Different Beds", types: ["Bed"] },
    { name: "Expand Link's Inventory by 10 Slots", types: ["Korok","Korok Forest"] },
    { name: "'Robbie's Research' Side Quest", types: ["Side Quest","Akkala","Camera"] },
    { name: "15 Cube Puzzle Koroks", types: ["Korok"] },
    { name: "Full Zora Set", types: ["Clothes","Zora Gear","Lanayru","Camera"] },
    { name: "Flamebreaker Helm ★", types: ["Clothes","Flame Gear","Eldin","Rupee","Great Fairy","Fireproof"] },
    { name: "Full Flamebreaker Set", types: ["Clothes","Flame Gear","Eldin","Rupee","Fireproof"] },
    { name: "10 Goal Ring Koroks", types: ["Korok"] },
    { name: "15 Monsters in Compendium", types: ["Camera","Compendium"] },
    { name: "1 Korok from every Region", types: ["Shrine"] },
    { name: "16 Shrines", types: ["Shrine"] },
    { name: "Zora Greaves ★", types: ["Clothes","Zora Gear","Great Fairy","Lizalfos","Camera"] },
    { name: "'The Skull's Eye' Shrine Quest", types: ["Shrine","Shrine Quest","Akkala","Camera"] },
    { name: "Full Barbarian Set", types: ["Clothes","Barbarian Gear"] },
    { name: "11 Side Quests", types: ["Side Quest"] },
    { name: "'Riddles of Hyrule' Side Quest", types: ["Side Quest","Woodland","Miniboss","Lynel","Korok Forest"] },
    { name: "35 Koroks", types: ["Korok"] },
    { name: "Activate 7 Towers", types: ["Tower"] },
    { name: "Collect 6 Picture Memories", types: ["Camera"] },
    { name: "Full Radiant Set", types: ["Clothes","Radiant Gear","Rupee","Gems","Gerudo Set"] },
    { name: "'Legendary Rabbit Trial' Side Quest", types: ["Side Quest","Woodland","Camera"] },
    { name: "'Slated for Upgrades' Side Quest", types: ["Side Quest","Hateno","Camera"] },
    { name: "Activate 8 Towers", types: ["Tower"] }
];
bingoList[23] = [
    { name: "40 Koroks", types: ["Korok"] },
    { name: "Mount 9 Different Creatures", types: ["Mount","Stamina"] },
    { name: "7 Heart Containers", types: ["Shrine","Heart"] },
    { name: "6 Shrine Quests", types: ["Shrine","Shrine Quest"] },
    { name: "'The Stolen Heirloom' Shrine Quest", types: ["Shrine","Shrine Quest","Dueling Peaks","Heirloom","Camera"] },
    { name: "20 Monsters in Compendium", types: ["Camera","Compendium"] },
    { name: "12 Side Quests", types: ["Side Quest"] },
    { name: "Activate 9 Towers", types: ["Tower"] },
    { name: "45 Koroks", types: ["Korok"] },
    { name: "7 Shrine Quests", types: ["Shrine","Shrine Quest"] },
    { name: "4 Stamina Vessels", types: ["Shrine","Stamina"] },
    { name: "Obtain a Horn from each Dragon", types: ["Dragon"] },
    { name: "15 Pinwheel Balloon Koroks", types: ["Korok"] },
    { name: "13 Side Quests", types: ["Side Quest"] },
    { name: "'The Eighth Heroine' Side Quest", types: ["Side Quest","Gerudo Set","Boots","Cold Resistance","Camera"] },
    { name: "Activate 10 Towers", types: ["Tower"] },
    { name: "50 Koroks", types: ["Korok"] },
    { name: "14 Side Quests", types: ["Side Quest"] },
    { name: "'The Forgotten Sword' Side Quest", types: ["Side Quest","Gerudo Set","Boots","Cold Resistance","Camera"] },
    { name: "15 Side Quests", types: ["Side Quest"] },
    { name: "8 Shrine Quests", types: ["Shrine","Shrine Quest"] },
    { name: "15 Goal Ring Koroks", types: ["Korok"] },
    { name: "'The Perfect Drink' Shrine Quest", types: ["Shrine","Shrine Quest","Gerudo Set"] },
    { name: "Snow Boots ★", types: ["Clothes","Gerudo Set","Boots","Side Quest","Great Fairy","Camera"] },
    { name: "'Leviathan Bones' Side Quest", types: ["Side Quest","Camera"] }
];
bingoList[24] = [
    { name: "1 Divine Beast Main Quest", types: ["Divine Beast","Main Quest"] },
    { name: "'Divine Beast Vah Medoh' Main Quest", types: ["Divine Beast","Main Quest","Medoh","Tabantha","Cold Resistance"] },
    { name: "'Divine Beast Vah Ruta' Main Quest", types: ["Divine Beast","Main Quest","Ruta","Lanayru"] },
    { name: "'Divine Beast Vah Naboris' Main Quest", types: ["Divine Beast","Main Quest","Naboris","Gerudo Set"] },
    { name: "'Divine Beast Vah Rudania' Main Quest", types: ["Divine Beast","Main Quest","Rudania","Eldin","Fireproof"] },
    { name: "Revali's Gale", types: ["Divine Beast","Main Quest","Medoh","Tabantha","Cold Resistance"] },
    { name: "Mipha's Grace", types: ["Divine Beast","Main Quest","Ruta","Lanayru"] },
    { name: "Urbosa's Fury", types: ["Divine Beast","Main Quest","Naboris","Gerudo Set"] },
    { name: "Daruk's Protection", types: ["Divine Beast","Main Quest","Rudania","Eldin","Fireproof"] },
    { name: "'Face the Frost Talus' Side Quest", types: ["Divine Beast","Main Quest","Medoh","Miniboss","Talus","Rupee","Gems","Side Quest","Tabantha","Hebra","Cold Resistance"] },
    { name: "'Recital at Warbler's Nest' Shrine Quest", types: ["Divine Beast","Main Quest","Medoh","Shrine","Shrine Quest","Tabantha"] },
    { name: "'Find Kheel' Side Quest", types: ["Divine Beast","Main Quest","Medoh","Side Quest","Tabantha"] },
    { name: "'The Ancient Rito Song' Shrine Quest", types: ["Divine Beast","Main Quest","Medoh","Shrine","Shrine Quest","Tabantha"] },
    { name: "20 Targets in Flight Range Minigame", types: ["Divine Beast","Main Quest","Medoh","Minigame","Tabantha","Cold Resistance"] },
    { name: "'A Wife Washed Away' Side Quest", types: ["Divine Beast","Main Quest","Ruta","Side Quest","Lanayru"] },
    { name: "'Frog Catching' Side Quest", types: ["Divine Beast","Main Quest","Ruta","Side Quest","Lanayru"] },
    { name: "'Zora Stone Monuments' Side Quest", types: ["Divine Beast","Main Quest","Ruta","Side Quest","Lanayru"] },
    { name: "'The Ceremonial Song' Shrine Quest", types: ["Divine Beast","Main Quest","Ruta","Shrine","Shrine Quest","Lanayru"] },
    { name: "'The Giant of Ralis Pond' Side Quest", types: ["Divine Beast","Main Quest","Ruta","Side Quest","Lanayru","Miniboss","Hinox"] },
    { name: "'The Search for Barta' Side Quest", types: ["Divine Beast","Main Quest","Naboris","Side Quest","Gerudo Set"] },
    { name: "'The Mystery Polluter' Side Quest", types: ["Divine Beast","Main Quest","Naboris","Side Quest","Gerudo Set"] },
    { name: "'The Undefeated Champ' Shrine Quest", types: ["Divine Beast","Main Quest","Naboris","Shrine","Shrine Quest","Gerudo Set"] },
    { name: "'The Jewel Trade' Side Quest", types: ["Divine Beast","Main Quest","Rudania","Side Quest","Eldin","Rupee","Gems","Fireproof"] },
    { name: "Spring-Loaded Hammer", types: ["Divine Beast","Main Quest","Equipment","Kilton"] },
    { name: "Remake a Champion's Weapon or Shield", types: ["Divine Beast","Main Quest","Equipment","Rupee","Gems"] }
];
bingoList[25] = [
    { name: "Defeat Dark Beast Ganon", types: ["Hyrule Castle"] },
    { name: "Pay 4 Great Faries", types: ["Great Fairy","Rupee","Dueling Peaks","Tabantha","Akkala","Wasteland"] },
    { name: "Kill 15 Hinox/Stalnox", types: ["Miniboss","Hinox"] },
    { name: "Kill 15 Talus", types: ["Miniboss","Talus","Gems"] },
    { name: "Kill 15 Lynel", types: ["Miniboss","Lynel"] },
    { name: "Tu Ka'loh, Korgu Chideh, Hawa Koth, Hia Miu, Saas Ko'sah", types: ["Shrine","Hyrule Castle","Eventide","Faron","Hebra","Wasteland","Akkala"] },
    { name: "2 Divine Beast Main Quest", types: ["Divine Beast"] },
    { name: "8 Main Quests", types: ["Divine Beast","Main Quest"] },
    { name: "'The Hobbies of the Rich' Side Quest", types: ["Side Quest", "Tarrey Town"] },
    { name: "'From the Ground Up' Side Quest", types: ["Side Quest", "Tarrey Town"] },
    { name: "'The Weapon Connoisseur' Side Quest", types: ["Side Quest", "Equipment"] },
    { name: "Capture 69 Compendium Pics", types: ["Camera", "Compendium"] },
    { name: "Obtain an 'Ancient' Weapon, Bow, and Shield", types: ["Equipment"] },
    { name: "Pray at every Goddess Statue (Fully Activated)", types: ["Shrine","Dragon"] }
];
module.exports = bingoList;
