// first, there is a list, separated by "|" of types, then the goal name
// 2 goals with the same type cannot appear in the same line 
var bingoList = [
    "Goddess Sword|Harp|Scale|Bow|Get Arrows from a Goddess Wall",
    "Goddess Sword|Harp|Scale|Bombs|Get Bombs from a Goddess Wall",
    "Goddess Sword|Scale|Potions|Dungeons||Bottles|Drink one of every Potion",
    "Goddess Sword|Cubes|5 Goddess Cubes in any Region",
    "Goddess Sword|Cubes|5 Lanayru Goddess Cubes",
    "Goddess Sword|Cubes|5 Eldin Goddess Cubes",
    "Goddess Sword|Cubes|5 Faron Goddess Cubes",
    "Goddess Sword|Cubes|10 Goddess Cubes",
    "Goddess Sword|Cubes|15 Goddess Cubes",
    "Goddess Sword|Cubes|20 Goddess Cubes",
    "Duplicate an Ampilus Egg",
    "Dungeons|Beat 2 Dungeons",
    "Harp|Complete any Silent Realm",
    "Trial|Harp|Complete Farore's Silent Realm",
    "Trial|Harp|Complete Nayru's Silent Realm",
    "Trial|Harp|Complete Din' Silent Realm",
    "Trial|Harp|Complete Goddess' Silent Realm",
    "Trial|Harp|Clear 2 Silent Realms",
    "Complete a check out of logic",
    "Finish the Sword Tutorial",
    "Minigames|Sword|28+ cuts at Bamboo Island",
    "Minigames|Complete any Minigame",
    "Minigames|Bug Heaven in under 1m30",
    "Minigames|Complete Fun Fun Island",
    "Minigames|Harp|Play the Harp Minigame",
    "Minigames|Clear a Thrill Digger board",
    "Mastersword|Sword|Go through the Gate of Time",
    "Hearts|8 Hearts",
    "Hearts|10 Hearts",
    "Hearts|12 Hearts",
    "Bottles|2 Bottles",
    "Bottles|3 Bottles",
    "Bottles|4 Bottles",
    "Harp|Thunderhead|Clear 2 Song Checks",
    "Dungeons|Skyview|Fire Sanctuary|Kill Ghirahim 1 or 2 with a dart",
    "Dungeons|Skyview|Bottles|Sacred Water",
    "Heart Medal|Pick up a Heart",
    "Find an inventory expansion",
    "SingleItem|Cursed Medal",
    "Treasures|Large Inventory Expansion",
    "Harp|Beat an unrequired Trial",
    "Dungeons|Full Clear a Dungeon",
    "Dungeons|1 Check in 5 Dungeons",
    "Dungeons|2 Checks in 4 Dungeons",
    "Crystals|50 Gratitude Crystals",
    "Crystals|60 Graditude Crystals",
    "Crystals|70 Gratitude Crystals",
    "Crystals|Clawshots|Beetle|80 Gratitude Crystals",
    "Crystals|5 loose Graditude Crystals",
    "Crystals|10 loose Graditude Crystals",
    "Crystals|Clawshots|Beetle|15 loose Graditude Crystals",
    "SingleItem|Stone of Trials",
    "Rupees|3 Golden Rupees",
    "Rupees|5 Golden Rupees",
    "Rupees|5 Silver Rupees",
    "Rupees|spend 2000 Rupees",
    "SingleItem|4 Earth Temple Keypieces", // technically not one item, but you have to get really lucky to get almost all of them
    "Statues|All Bird Statues in any Region",
    "Statues|Both Deep Woods Bird Statues",
    "Statues|20 Bird Statues",
    "Statues|Clawshots|All Sandsea Bird Statues",
    "Statues|Faron|5 Faron Bird statues",
    "Statues|Lanayru|8 Lanayru Bird Statues",
    "Gust Bellows|Turn a Windmill",
    "Pouch|6 pouch slots",
    "Pouch|7 Pouch slots",
    "Treasures|Bug Net|Upgrade 1 B-Wheel item",
    "Treasures|Bug Net|Upgrade 2 B-Wheel item",
    "Treasures|Upgrades|Upgrade 3 different Items",
    "Treasures|Upgrades|Upgrade Items 3 times",
    "Treasures|Upgrades|Upgrade 1 Shield",
    "Bug Net|Upgrades|Upgrade 3 different Potions",
    "Bug Net|Upgrades|Upgrade 4 different Potions",
    "Medals|3 medals",
    "Medals|4 medals",
    "Medals|5 medals",
    "Upgrades|Bug Net|Treasures|Shields|All Wooden Shields",
    "Upgrades|Bug Net|Treasures|Shields|Bug Net|All Iron Shields",
    "Upgrades|Bug Net|Treasures|Shields|3 Unique Shields",
    "Upgrades|Bug Net|Treasures|Shields|5 Unique Shields",
    "Bug Net|Catch 50 of any bug",
    "Bug Net|10 Unique bugs",
    "Treasures|10 Unique Treasures",
    "Treasures|One of every Treasure",
    "Quests|2 Scrapper Quests",
    "Defeat visible Bilocyte",
    "Life Tree Seedling",
    "Keys|obtain 3 small Keys",
    "Keys|obtain 4 small Keys",
    "Keys|obtain 5 small Keys",
    "Dungeons|Boss Keys|obtain 2 Boss Keys",
    "Dungeons|Boss Keys|obtain 3 Boss Keys",
    "Maps|obtain 2 Maps",
    "Maps|obtain 3 Maps",
    "Defeat one evil Robot",
    "Defeat both evil Robots",
    "Dungeons|Defeat all 3 Magmanos",
    "Any Projectile",
    "Defeat a Lizalfos",
    "Defeat a blue Bokoblin",
	"SingleItem|Find the Tumbleweed"
];

module.exports = bingoList;
